package Mumie::XML::Characters;

# Author: Tilman Rassy <rassy@math.tu-berlin.de>

# $Id: Characters.pm,v 1.2 2007/07/11 15:58:55 grudzin Exp $

# The MIT License (MIT)
# 
# Copyright (c) 2010 Technische Universitaet Berlin
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require Exporter;

@ISA = qw(Exporter);
@EXPORT_OK = qw
  (
   %entities_vs_numcodes
   %numcodes_vs_entities
   %chars_vs_entities
   %entities_vs_chars
   entities_to_numcodes
   numcodes_to_entities
   chars_to_numcodes
   numcodes_to_chars
   chars_to_entities
   entities_to_chars
   quote_xml
  );


# --------------------------------------------------------------------------------
# The init function
# --------------------------------------------------------------------------------

my $_entity_name_regexp;
my $_entity_regexp;
my $_numcode_value_regexp;
my $_numcode_regexp;

sub init
  {
    return() if ( $init_done );

    # Source:  The XHTML plus Math 1.1 DTD, file: xhtml-math11.dtd,
    #          cvs id: xhtml-1,v 1.1 2000/10/31 19:52:09 davidc Exp
    %entities_vs_numcodes =
      (
       'AElig' => '&#198;',
       'Aacute' => '&#193;',
       'Abreve' => '&#x00102;',
       'Acirc' => '&#194;',
       'Acy' => '&#x00410;',
       'Afr' => '&#x1D504;',
       'Agrave' => '&#192;',
       'Alpha' => '&#913;',
       'Amacr' => '&#x00100;',
       'And' => '&#x02A53;',
       'Aogon' => '&#x00104;',
       'Aopf' => '&#x1D538;',
       'ApplyFunction' => '&#x02061;',
       'Aring' => '&#197;',
       'Ascr' => '&#x1D49C;',
       'Assign' => '&#x02254;',
       'Atilde' => '&#195;',
       'Auml' => '&#196;',
       'Backslash' => '&#x02216;',
       'Barv' => '&#x02AE7;',
       'Barwed' => '&#x02306;',
       'Bcy' => '&#x00411;',
       'Because' => '&#x02235;',
       'Bernoullis' => '&#x0212C;',
       'Beta' => '&#914;',
       'Bfr' => '&#x1D505;',
       'Bopf' => '&#x1D539;',
       'Breve' => '&#x002D8;',
       'Bscr' => '&#x0212C;',
       'Bumpeq' => '&#x0224E;',
       'CHcy' => '&#x00427;',
       'Cacute' => '&#x00106;',
       'Cap' => '&#x022D2;',
       'CapitalDifferentialD' => '&#x02145;',
       'Cayleys' => '&#x0212D;',
       'Ccaron' => '&#x0010C;',
       'Ccedil' => '&#199;',
       'Ccirc' => '&#x00108;',
       'Cconint' => '&#x02230;',
       'Cdot' => '&#x0010A;',
       'Cedilla' => '&#x000B8;',
       'CenterDot' => '&#x000B7;',
       'Cfr' => '&#x0212D;',
       'Chi' => '&#935;',
       'CircleDot' => '&#x02299;',
       'CircleMinus' => '&#x02296;',
       'CirclePlus' => '&#x02295;',
       'CircleTimes' => '&#x02297;',
       'ClockwiseContourIntegral' => '&#x02232;',
       'CloseCurlyDoubleQuote' => '&#x0201D;',
       'CloseCurlyQuote' => '&#x02019;',
       'Colon' => '&#x02237;',
       'Colone' => '&#x02A74;',
       'Congruent' => '&#x02261;',
       'Conint' => '&#x0222F;',
       'ContourIntegral' => '&#x0222E;',
       'Copf' => '&#x02102;',
       'Coproduct' => '&#x02210;',
       'CounterClockwiseContourIntegral' => '&#x02233;',
       'Cross' => '&#x02A2F;',
       'Cscr' => '&#x1D49E;',
       'Cup' => '&#x022D3;',
       'CupCap' => '&#x0224D;',
       'DD' => '&#x02145;',
       'DDotrahd' => '&#x02911;',
       'DJcy' => '&#x00402;',
       'DScy' => '&#x00405;',
       'DZcy' => '&#x0040F;',
       'Dagger' => '&#8225;',
       'Darr' => '&#x021A1;',
       'Dashv' => '&#x02AE4;',
       'Dcaron' => '&#x0010E;',
       'Dcy' => '&#x00414;',
       'Del' => '&#x02207;',
       'Delta' => '&#916;',
       'Dfr' => '&#x1D507;',
       'DiacriticalAcute' => '&#x000B4;',
       'DiacriticalDot' => '&#x002D9;',
       'DiacriticalDoubleAcute' => '&#x002DD;',
       'DiacriticalGrave' => '&#x00060;',
       'DiacriticalTilde' => '&#x002DC;',
       'Diamond' => '&#x022C4;',
       'DifferentialD' => '&#x02146;',
       'Dopf' => '&#x1D53B;',
       'Dot' => '&#x000A8;',
       'DotDot' => '&#x020DC;',
       'DotEqual' => '&#x02250;',
       'DoubleContourIntegral' => '&#x0222F;',
       'DoubleDot' => '&#x000A8;',
       'DoubleDownArrow' => '&#x021D3;',
       'DoubleLeftArrow' => '&#x021D0;',
       'DoubleLeftRightArrow' => '&#x021D4;',
       'DoubleLeftTee' => '&#x02AE4;',
       'DoubleLongLeftArrow' => '&#x0F579;',
       'DoubleLongLeftRightArrow' => '&#x0F57B;',
       'DoubleLongRightArrow' => '&#x0F57A;',
       'DoubleRightArrow' => '&#x021D2;',
       'DoubleRightTee' => '&#x022A8;',
       'DoubleUpArrow' => '&#x021D1;',
       'DoubleUpDownArrow' => '&#x021D5;',
       'DoubleVerticalBar' => '&#x02225;',
       'DownArrow' => '&#x02193;',
       'DownArrowBar' => '&#x02913;',
       'DownArrowUpArrow' => '&#x021F5;',
       'DownBreve' => '&#x00311;',
       'DownLeftRightVector' => '&#x02950;',
       'DownLeftTeeVector' => '&#x0295E;',
       'DownLeftVector' => '&#x021BD;',
       'DownLeftVectorBar' => '&#x02956;',
       'DownRightTeeVector' => '&#x0295F;',
       'DownRightVector' => '&#x021C1;',
       'DownRightVectorBar' => '&#x02957;',
       'DownTee' => '&#x022A4;',
       'DownTeeArrow' => '&#x021A7;',
       'Downarrow' => '&#x021D3;',
       'Dscr' => '&#x1D49F;',
       'Dstrok' => '&#x00110;',
       'ENG' => '&#x0014A;',
       'ETH' => '&#208;',
       'Eacute' => '&#201;',
       'Ecaron' => '&#x0011A;',
       'Ecirc' => '&#202;',
       'Ecy' => '&#x0042D;',
       'Edot' => '&#x00116;',
       'Efr' => '&#x1D508;',
       'Egrave' => '&#200;',
       'Element' => '&#x02208;',
       'Emacr' => '&#x00112;',
       'EmptySmallSquare' => '&#x025FD;',
       'EmptyVerySmallSquare' => '&#x0F59C;',
       'Eogon' => '&#x00118;',
       'Eopf' => '&#x1D53C;',
       'Epsilon' => '&#917;',
       'Equal' => '&#x02A75;',
       'EqualTilde' => '&#x02242;',
       'Equilibrium' => '&#x021CC;',
       'Escr' => '&#x02130;',
       'Esim' => '&#x02A73;',
       'Eta' => '&#919;',
       'Euml' => '&#203;',
       'Exists' => '&#x02203;',
       'ExponentialE' => '&#x02147;',
       'Fcy' => '&#x00424;',
       'Ffr' => '&#x1D509;',
       'FilledSmallSquare' => '&#x025FE;',
       'FilledVerySmallSquare' => '&#x0F59B;',
       'Fopf' => '&#x1D53D;',
       'ForAll' => '&#x02200;',
       'Fouriertrf' => '&#x02131;',
       'Fscr' => '&#x02131;',
       'GJcy' => '&#x00403;',
       'Gamma' => '&#915;',
       'Gammad' => '&#x003DC;',
       'Gbreve' => '&#x0011E;',
       'Gcedil' => '&#x00122;',
       'Gcirc' => '&#x0011C;',
       'Gcy' => '&#x00413;',
       'Gdot' => '&#x00120;',
       'Gfr' => '&#x1D50A;',
       'Gg' => '&#x022D9;',
       'Gopf' => '&#x1D53E;',
       'GreaterEqual' => '&#x02265;',
       'GreaterEqualLess' => '&#x022DB;',
       'GreaterFullEqual' => '&#x02267;',
       'GreaterGreater' => '&#x02AA2;',
       'GreaterLess' => '&#x02277;',
       'GreaterSlantEqual' => '&#x02A7E;',
       'GreaterTilde' => '&#x02273;',
       'Gscr' => '&#x1D4A2;',
       'Gt' => '&#x0226B;',
       'HARDcy' => '&#x0042A;',
       'Hacek' => '&#x002C7;',
       'Hat' => '&#x00302;',
       'Hcirc' => '&#x00124;',
       'Hfr' => '&#x0210C;',
       'HilbertSpace' => '&#x0210B;',
       'Hopf' => '&#x0210D;',
       'HorizontalLine' => '&#x02500;',
       'Hscr' => '&#x0210B;',
       'Hstrok' => '&#x00126;',
       'HumpDownHump' => '&#x0224E;',
       'HumpEqual' => '&#x0224F;',
       'IEcy' => '&#x00415;',
       'IJlig' => '&#x00132;',
       'IOcy' => '&#x00401;',
       'Iacute' => '&#205;',
       'Icirc' => '&#206;',
       'Icy' => '&#x00418;',
       'Idot' => '&#x00130;',
       'Ifr' => '&#x02111;',
       'Igrave' => '&#204;',
       'Im' => '&#x02111;',
       'Imacr' => '&#x0012A;',
       'ImaginaryI' => '&#x02148;',
       'Implies' => '&#x021D2;',
       'Int' => '&#x0222C;',
       'Integral' => '&#x0222B;',
       'Intersection' => '&#x022C2;',
       'InvisibleComma' => '&#x0200B;',
       'InvisibleTimes' => '&#x02062;',
       'Iogon' => '&#x0012E;',
       'Iopf' => '&#x1D540;',
       'Iota' => '&#921;',
       'Iscr' => '&#x02110;',
       'Itilde' => '&#x00128;',
       'Iukcy' => '&#x00406;',
       'Iuml' => '&#207;',
       'Jcirc' => '&#x00134;',
       'Jcy' => '&#x00419;',
       'Jfr' => '&#x1D50D;',
       'Jopf' => '&#x1D541;',
       'Jscr' => '&#x1D4A5;',
       'Jsercy' => '&#x00408;',
       'Jukcy' => '&#x00404;',
       'KHcy' => '&#x00425;',
       'KJcy' => '&#x0040C;',
       'Kappa' => '&#922;',
       'Kcedil' => '&#x00136;',
       'Kcy' => '&#x0041A;',
       'Kfr' => '&#x1D50E;',
       'Kopf' => '&#x1D542;',
       'Kscr' => '&#x1D4A6;',
       'LJcy' => '&#x00409;',
       'Lacute' => '&#x00139;',
       'Lambda' => '&#923;',
       'Lang' => '&#x0300A;',
       'Laplacetrf' => '&#x02112;',
       'Larr' => '&#x0219E;',
       'Lcaron' => '&#x0013D;',
       'Lcedil' => '&#x0013B;',
       'Lcy' => '&#x0041B;',
       'LeftAngleBracket' => '&#x02329;',
       'LeftArrow' => '&#x02190;',
       'LeftArrowBar' => '&#x021E4;',
       'LeftArrowRightArrow' => '&#x021C6;',
       'LeftCeiling' => '&#x02308;',
       'LeftDoubleBracket' => '&#x0301A;',
       'LeftDownTeeVector' => '&#x02961;',
       'LeftDownVector' => '&#x021C3;',
       'LeftDownVectorBar' => '&#x02959;',
       'LeftFloor' => '&#x0230A;',
       'LeftRightArrow' => '&#x02194;',
       'LeftRightVector' => '&#x0294E;',
       'LeftTee' => '&#x022A3;',
       'LeftTeeArrow' => '&#x021A4;',
       'LeftTeeVector' => '&#x0295A;',
       'LeftTriangle' => '&#x022B2;',
       'LeftTriangleBar' => '&#x029CF;',
       'LeftTriangleEqual' => '&#x022B4;',
       'LeftUpDownVector' => '&#x02951;',
       'LeftUpTeeVector' => '&#x02960;',
       'LeftUpVector' => '&#x021BF;',
       'LeftUpVectorBar' => '&#x02958;',
       'LeftVector' => '&#x021BC;',
       'LeftVectorBar' => '&#x02952;',
       'Leftarrow' => '&#x021D0;',
       'Leftrightarrow' => '&#x021D4;',
       'LessEqualGreater' => '&#x022DA;',
       'LessFullEqual' => '&#x02266;',
       'LessGreater' => '&#x02276;',
       'LessLess' => '&#x02AA1;',
       'LessSlantEqual' => '&#x02A7D;',
       'LessTilde' => '&#x02272;',
       'Lfr' => '&#x1D50F;',
       'Ll' => '&#x022D8;',
       'Lleftarrow' => '&#x021DA;',
       'Lmidot' => '&#x0013F;',
       'LongLeftArrow' => '&#x0F576;',
       'LongLeftRightArrow' => '&#x0F578;',
       'LongRightArrow' => '&#x0F577;',
       'Longleftarrow' => '&#x0F579;',
       'Longleftrightarrow' => '&#x0F57B;',
       'Longrightarrow' => '&#x0F57A;',
       'Lopf' => '&#x1D543;',
       'LowerLeftArrow' => '&#x02199;',
       'LowerRightArrow' => '&#x02198;',
       'Lscr' => '&#x02112;',
       'Lsh' => '&#x021B0;',
       'Lstrok' => '&#x00141;',
       'Lt' => '&#x0226A;',
       'Map' => '&#x02905;',
       'Mcy' => '&#x0041C;',
       'MediumSpace' => '&#x0205F;',
       'Mellintrf' => '&#x02133;',
       'Mfr' => '&#x1D510;',
       'MinusPlus' => '&#x02213;',
       'Mopf' => '&#x1D544;',
       'Mscr' => '&#x02133;',
       'Mu' => '&#924;',
       'NJcy' => '&#x0040A;',
       'Nacute' => '&#x00143;',
       'Ncaron' => '&#x00147;',
       'Ncedil' => '&#x00145;',
       'Ncy' => '&#x0041D;',
       'NegativeMediumSpace' => '&#x0205F;&#x0FE00;',
       'NegativeThickSpace' => '&#x02005;&#x0FE00;',
       'NegativeThinSpace' => '&#x02009;&#x0FE00;',
       'NegativeVeryThinSpace' => '&#x0200A;&#x0FE00;',
       'NestedGreaterGreater' => '&#x0226B;',
       'NestedLessLess' => '&#x0226A;',
       'NewLine' => '&#x0000A;',
       'Nfr' => '&#x1D511;',
       'NoBreak' => '&#x0FEFF;',
       'NonBreakingSpace' => '&#x000A0;',
       'Nopf' => '&#x02115;',
       'Not' => '&#x02AEC;',
       'NotCongruent' => '&#x02262;',
       'NotCupCap' => '&#x0226D;',
       'NotDoubleVerticalBar' => '&#x02226;',
       'NotElement' => '&#x02209;',
       'NotEqual' => '&#x02260;',
       'NotEqualTilde' => '&#x02242;&#x00338;',
       'NotExists' => '&#x02204;',
       'NotGreater' => '&#x0226F;',
       'NotGreaterEqual' => '&#x02271;&#x020E5;',
       'NotGreaterFullEqual' => '&#x02270;',
       'NotGreaterGreater' => '&#x0226B;&#x00338;&#x0FE00;',
       'NotGreaterLess' => '&#x02279;',
       'NotGreaterSlantEqual' => '&#x02271;',
       'NotGreaterTilde' => '&#x02275;',
       'NotHumpDownHump' => '&#x0224E;&#x00338;',
       'NotHumpEqual' => '&#x0224F;&#x00338;',
       'NotLeftTriangle' => '&#x022EA;',
       'NotLeftTriangleBar' => '&#x029CF;&#x00338;',
       'NotLeftTriangleEqual' => '&#x022EC;',
       'NotLess' => '&#x0226E;',
       'NotLessEqual' => '&#x02270;&#x020E5;',
       'NotLessGreater' => '&#x02278;',
       'NotLessLess' => '&#x0226A;&#x00338;&#x0FE00;',
       'NotLessSlantEqual' => '&#x02270;',
       'NotLessTilde' => '&#x02274;',
       'NotNestedGreaterGreater' => '&#x024A2;&#x00338;',
       'NotNestedLessLess' => '&#x024A1;&#x00338;',
       'NotPrecedes' => '&#x02280;',
       'NotPrecedesEqual' => '&#x02AAF;&#x00338;',
       'NotPrecedesSlantEqual' => '&#x022E0;',
       'NotReverseElement' => '&#x0220C;',
       'NotRightTriangle' => '&#x022EB;',
       'NotRightTriangleBar' => '&#x029D0;&#x00338;',
       'NotRightTriangleEqual' => '&#x022ED;',
       'NotSquareSubset' => '&#x0228F;&#x00338;',
       'NotSquareSubsetEqual' => '&#x022E2;',
       'NotSquareSuperset' => '&#x02290;&#x00338;',
       'NotSquareSupersetEqual' => '&#x022E3;',
       'NotSubset' => '&#x02284;',
       'NotSubsetEqual' => '&#x02288;',
       'NotSucceeds' => '&#x02281;',
       'NotSucceedsEqual' => '&#x02AB0;&#x00338;',
       'NotSucceedsSlantEqual' => '&#x022E1;',
       'NotSucceedsTilde' => '&#x0227F;&#x00338;',
       'NotSuperset' => '&#x02285;',
       'NotSupersetEqual' => '&#x02289;',
       'NotTilde' => '&#x02241;',
       'NotTildeEqual' => '&#x02244;',
       'NotTildeFullEqual' => '&#x02247;',
       'NotTildeTilde' => '&#x02249;',
       'NotVerticalBar' => '&#x02224;',
       'Nscr' => '&#x1D4A9;',
       'Ntilde' => '&#209;',
       'Nu' => '&#925;',
       'OElig' => '&#338;',
       'Oacute' => '&#211;',
       'Ocirc' => '&#212;',
       'Ocy' => '&#x0041E;',
       'Odblac' => '&#x00150;',
       'Ofr' => '&#x1D512;',
       'Ograve' => '&#210;',
       'Omacr' => '&#x0014C;',
       'Omega' => '&#937;',
       'Omicron' => '&#927;',
       'Oopf' => '&#x1D546;',
       'OpenCurlyDoubleQuote' => '&#x0201C;',
       'OpenCurlyQuote' => '&#x02018;',
       'Or' => '&#x02A54;',
       'Oscr' => '&#x1D4AA;',
       'Oslash' => '&#216;',
       'Otilde' => '&#213;',
       'Otimes' => '&#x02A37;',
       'Ouml' => '&#214;',
       'OverBar' => '&#x000AF;',
       'OverBrace' => '&#x0FE37;',
       'OverBracket' => '&#x023B4;',
       'OverParenthesis' => '&#x0FE35;',
       'PartialD' => '&#x02202;',
       'Pcy' => '&#x0041F;',
       'Pfr' => '&#x1D513;',
       'Phi' => '&#934;',
       'Pi' => '&#928;',
       'PlusMinus' => '&#x000B1;',
       'Poincareplane' => '&#x0210C;',
       'Popf' => '&#x02119;',
       'Pr' => '&#x02ABB;',
       'Precedes' => '&#x0227A;',
       'PrecedesEqual' => '&#x02AAF;',
       'PrecedesSlantEqual' => '&#x0227C;',
       'PrecedesTilde' => '&#x0227E;',
       'Prime' => '&#8243;',
       'Product' => '&#x0220F;',
       'Proportion' => '&#x02237;',
       'Proportional' => '&#x0221D;',
       'Pscr' => '&#x1D4AB;',
       'Psi' => '&#936;',
       'Qfr' => '&#x1D514;',
       'Qopf' => '&#x0211A;',
       'Qscr' => '&#x1D4AC;',
       'RBarr' => '&#x02910;',
       'Racute' => '&#x00154;',
       'Rang' => '&#x0300B;',
       'Rarr' => '&#x021A0;',
       'Rarrtl' => '&#x02916;',
       'Rcaron' => '&#x00158;',
       'Rcedil' => '&#x00156;',
       'Rcy' => '&#x00420;',
       'Re' => '&#x0211C;',
       'ReverseElement' => '&#x0220B;',
       'ReverseEquilibrium' => '&#x021CB;',
       'ReverseUpEquilibrium' => '&#x0296F;',
       'Rfr' => '&#x0211C;',
       'Rho' => '&#929;',
       'RightAngleBracket' => '&#x0232A;',
       'RightArrow' => '&#x02192;',
       'RightArrowBar' => '&#x021E5;',
       'RightArrowLeftArrow' => '&#x021C4;',
       'RightCeiling' => '&#x02309;',
       'RightDoubleBracket' => '&#x0301B;',
       'RightDownTeeVector' => '&#x0295D;',
       'RightDownVector' => '&#x021C2;',
       'RightDownVectorBar' => '&#x02955;',
       'RightFloor' => '&#x0230B;',
       'RightTee' => '&#x022A2;',
       'RightTeeArrow' => '&#x021A6;',
       'RightTeeVector' => '&#x0295B;',
       'RightTriangle' => '&#x022B3;',
       'RightTriangleBar' => '&#x029D0;',
       'RightTriangleEqual' => '&#x022B5;',
       'RightUpDownVector' => '&#x0294F;',
       'RightUpTeeVector' => '&#x0295C;',
       'RightUpVector' => '&#x021BE;',
       'RightUpVectorBar' => '&#x02954;',
       'RightVector' => '&#x021C0;',
       'RightVectorBar' => '&#x02953;',
       'Rightarrow' => '&#x021D2;',
       'Ropf' => '&#x0211D;',
       'RoundImplies' => '&#x02970;',
       'Rrightarrow' => '&#x021DB;',
       'Rscr' => '&#x0211B;',
       'Rsh' => '&#x021B1;',
       'RuleDelayed' => '&#x029F4;',
       'SHCHcy' => '&#x00429;',
       'SHcy' => '&#x00428;',
       'SOFTcy' => '&#x0042C;',
       'Sacute' => '&#x0015A;',
       'Sc' => '&#x02ABC;',
       'Scaron' => '&#352;',
       'Scedil' => '&#x0015E;',
       'Scirc' => '&#x0015C;',
       'Scy' => '&#x00421;',
       'Sfr' => '&#x1D516;',
       'ShortDownArrow' => '&#x02304;&#x0FE00;',
       'ShortLeftArrow' => '&#x02190;&#x0FE00;',
       'ShortRightArrow' => '&#x02192;&#x0FE00;',
       'ShortUpArrow' => '&#x02303;&#x0FE00;',
       'Sigma' => '&#931;',
       'SmallCircle' => '&#x02218;',
       'Sopf' => '&#x1D54A;',
       'Sqrt' => '&#x0221A;',
       'Square' => '&#x025A1;',
       'SquareIntersection' => '&#x02293;',
       'SquareSubset' => '&#x0228F;',
       'SquareSubsetEqual' => '&#x02291;',
       'SquareSuperset' => '&#x02290;',
       'SquareSupersetEqual' => '&#x02292;',
       'SquareUnion' => '&#x02294;',
       'Sscr' => '&#x1D4AE;',
       'Star' => '&#x022C6;',
       'Sub' => '&#x022D0;',
       'Subset' => '&#x022D0;',
       'SubsetEqual' => '&#x02286;',
       'Succeeds' => '&#x0227B;',
       'SucceedsEqual' => '&#x0227D;',
       'SucceedsSlantEqual' => '&#x0227D;',
       'SucceedsTilde' => '&#x0227F;',
       'SuchThat' => '&#x0220B;',
       'Sum' => '&#x02211;',
       'Sup' => '&#x022D1;',
       'Superset' => '&#x02283;',
       'SupersetEqual' => '&#x02287;',
       'Supset' => '&#x022D1;',
       'THORN' => '&#222;',
       'TSHcy' => '&#x0040B;',
       'TScy' => '&#x00426;',
       'Tab' => '&#x00009;',
       'Tau' => '&#932;',
       'Tcaron' => '&#x00164;',
       'Tcedil' => '&#x00162;',
       'Tcy' => '&#x00422;',
       'Tfr' => '&#x1D517;',
       'Therefore' => '&#x02234;',
       'Theta' => '&#920;',
       'ThickSpace' => '&#x02009;&#x0200A;&#x0200A;',
       'ThinSpace' => '&#x02009;',
       'Tilde' => '&#x0223C;',
       'TildeEqual' => '&#x02243;',
       'TildeFullEqual' => '&#x02245;',
       'TildeTilde' => '&#x02248;',
       'Topf' => '&#x1D54B;',
       'TripleDot' => '&#x020DB;',
       'Tscr' => '&#x1D4AF;',
       'Tstrok' => '&#x00166;',
       'Uacute' => '&#218;',
       'Uarr' => '&#x0219F;',
       'Uarrocir' => '&#x02949;',
       'Ubrcy' => '&#x0040E;',
       'Ubreve' => '&#x0016C;',
       'Ucirc' => '&#219;',
       'Ucy' => '&#x00423;',
       'Udblac' => '&#x00170;',
       'Ufr' => '&#x1D518;',
       'Ugrave' => '&#217;',
       'Umacr' => '&#x0016A;',
       'UnderBar' => '&#x00332;',
       'UnderBrace' => '&#x0FE38;',
       'UnderBracket' => '&#x023B5;',
       'UnderParenthesis' => '&#x0FE36;',
       'Union' => '&#x022C3;',
       'UnionPlus' => '&#x0228E;',
       'Uogon' => '&#x00172;',
       'Uopf' => '&#x1D54C;',
       'UpArrow' => '&#x02191;',
       'UpArrowBar' => '&#x02912;',
       'UpArrowDownArrow' => '&#x021C5;',
       'UpDownArrow' => '&#x02195;',
       'UpEquilibrium' => '&#x0296E;',
       'UpTee' => '&#x022A5;',
       'UpTeeArrow' => '&#x021A5;',
       'Uparrow' => '&#x021D1;',
       'Updownarrow' => '&#x021D5;',
       'UpperLeftArrow' => '&#x02196;',
       'UpperRightArrow' => '&#x02197;',
       'Upsi' => '&#x003D2;',
       'Upsilon' => '&#933;',
       'Uring' => '&#x0016E;',
       'Uscr' => '&#x1D4B0;',
       'Utilde' => '&#x00168;',
       'Uuml' => '&#220;',
       'VDash' => '&#x022AB;',
       'Vbar' => '&#x02AEB;',
       'Vcy' => '&#x00412;',
       'Vdash' => '&#x022A9;',
       'Vdashl' => '&#x02AE6;',
       'Vee' => '&#x022C1;',
       'Verbar' => '&#x02016;',
       'Vert' => '&#x02016;',
       'VerticalBar' => '&#x02223;',
       'VerticalLine' => '&#x0007C;',
       'VerticalSeparator' => '&#x02758;',
       'VerticalTilde' => '&#x02240;',
       'VeryThinSpace' => '&#x0200A;',
       'Vfr' => '&#x1D519;',
       'Vopf' => '&#x1D54D;',
       'Vscr' => '&#x1D4B1;',
       'Vvdash' => '&#x022AA;',
       'Wcirc' => '&#x00174;',
       'Wedge' => '&#x022C0;',
       'Wfr' => '&#x1D51A;',
       'Wopf' => '&#x1D54E;',
       'Wscr' => '&#x1D4B2;',
       'Xfr' => '&#x1D51B;',
       'Xi' => '&#926;',
       'Xopf' => '&#x1D54F;',
       'Xscr' => '&#x1D4B3;',
       'YAcy' => '&#x0042F;',
       'YIcy' => '&#x00407;',
       'YUcy' => '&#x0042E;',
       'Yacute' => '&#221;',
       'Ycirc' => '&#x00176;',
       'Ycy' => '&#x0042B;',
       'Yfr' => '&#x1D51C;',
       'Yopf' => '&#x1D550;',
       'Yscr' => '&#x1D4B4;',
       'Yuml' => '&#376;',
       'ZHcy' => '&#x00416;',
       'Zacute' => '&#x00179;',
       'Zcaron' => '&#x0017D;',
       'Zcy' => '&#x00417;',
       'Zdot' => '&#x0017B;',
       'ZeroWidthSpace' => '&#x0200B;',
       'Zeta' => '&#918;',
       'Zfr' => '&#x02128;',
       'Zopf' => '&#x02124;',
       'Zscr' => '&#x1D4B5;',
       'aacute' => '&#225;',
       'abreve' => '&#x00103;',
       'ac' => '&#x0290F;',
       'acE' => '&#x029DB;',
       'acd' => '&#x0223F;',
       'acirc' => '&#226;',
       'acute' => '&#180;',
       'acy' => '&#x00430;',
       'aelig' => '&#230;',
       'af' => '&#x02061;',
       'afr' => '&#x1D51E;',
       'agrave' => '&#224;',
       'alefsym' => '&#8501;',
       'aleph' => '&#x02135;',
       'alpha' => '&#945;',
       'amacr' => '&#x00101;',
       'amalg' => '&#x02A3F;',
       'amp' => '&#38;',
       'and' => '&#8743;',
       'andand' => '&#x02A55;',
       'andd' => '&#x02A5C;',
       'andslope' => '&#x02A58;',
       'andv' => '&#x02A5A;',
       'ang' => '&#8736;',
       'ange' => '&#x029A4;',
       'angle' => '&#x02220;',
       'angmsd' => '&#x02221;',
       'angmsdaa' => '&#x029A8;',
       'angmsdab' => '&#x029A9;',
       'angmsdac' => '&#x029AA;',
       'angmsdad' => '&#x029AB;',
       'angmsdae' => '&#x029AC;',
       'angmsdaf' => '&#x029AD;',
       'angmsdag' => '&#x029AE;',
       'angmsdah' => '&#x029AF;',
       'angrt' => '&#x0221F;',
       'angrtvb' => '&#x0299D;&#x0FE00;',
       'angrtvbd' => '&#x0299D;',
       'angsph' => '&#x02222;',
       'angst' => '&#x0212B;',
       'angzarr' => '&#x0237C;',
       'aogon' => '&#x00105;',
       'aopf' => '&#x1D552;',
       'ap' => '&#x02248;',
       'apE' => '&#x0224A;',
       'apacir' => '&#x02A6F;',
       'ape' => '&#x0224A;',
       'apid' => '&#x0224B;',
       'apos' => '&#x00027;',
       'approx' => '&#x02248;',
       'approxeq' => '&#x0224A;',
       'aring' => '&#229;',
       'ascr' => '&#x1D4B6;',
       'ast' => '&#x0002A;',
       'asymp' => '&#8776;',
       'atilde' => '&#227;',
       'auml' => '&#228;',
       'awconint' => '&#x02233;',
       'awint' => '&#x02A11;',
       'bNot' => '&#x02AED;',
       'backcong' => '&#x0224C;',
       'backepsilon' => '&#x003F6;',
       'backprime' => '&#x02035;',
       'backsim' => '&#x0223D;',
       'backsimeq' => '&#x022CD;',
       'barvee' => '&#x022BD;',
       'barwed' => '&#x022BC;',
       'barwedge' => '&#x022BC;',
       'bbrk' => '&#x023B5;',
       'bcong' => '&#x0224C;',
       'bcy' => '&#x00431;',
       'bdquo' => '&#8222;',
       'becaus' => '&#x02235;',
       'because' => '&#x02235;',
       'bemptyv' => '&#x029B0;',
       'bepsi' => '&#x003F6;',
       'bernou' => '&#x0212C;',
       'beta' => '&#946;',
       'beth' => '&#x02136;',
       'between' => '&#x0226C;',
       'bfr' => '&#x1D51F;',
       'bigcap' => '&#x022C2;',
       'bigcirc' => '&#x025EF;',
       'bigcup' => '&#x022C3;',
       'bigodot' => '&#x02299;',
       'bigoplus' => '&#x02295;',
       'bigotimes' => '&#x02297;',
       'bigsqcup' => '&#x02294;',
       'bigstar' => '&#x02605;',
       'bigtriangledown' => '&#x025BD;',
       'bigtriangleup' => '&#x025B3;',
       'biguplus' => '&#x0228E;',
       'bigvee' => '&#x022C1;',
       'bigwedge' => '&#x022C0;',
       'bkarow' => '&#x0290D;',
       'blacklozenge' => '&#x029EB;',
       'blacksquare' => '&#x025AA;',
       'blacktriangle' => '&#x025B4;',
       'blacktriangledown' => '&#x025BE;',
       'blacktriangleleft' => '&#x025C2;',
       'blacktriangleright' => '&#x025B8;',
       'blank' => '&#x02423;',
       'blk12' => '&#x02592;',
       'blk14' => '&#x02591;',
       'blk34' => '&#x02593;',
       'block' => '&#x02588;',
       'bne' => '&#x0003D;&#x020E5;',
       'bnequiv' => '&#x02261;&#x020E5;',
       'bnot' => '&#x02310;',
       'bopf' => '&#x1D553;',
       'bot' => '&#x022A5;',
       'bottom' => '&#x022A5;',
       'bowtie' => '&#x022C8;',
       'boxDL' => '&#x02557;',
       'boxDR' => '&#x02554;',
       'boxDl' => '&#x02556;',
       'boxDr' => '&#x02553;',
       'boxH' => '&#x02550;',
       'boxHD' => '&#x02566;',
       'boxHU' => '&#x02569;',
       'boxHd' => '&#x02564;',
       'boxHu' => '&#x02567;',
       'boxUL' => '&#x0255D;',
       'boxUR' => '&#x0255A;',
       'boxUl' => '&#x0255C;',
       'boxUr' => '&#x02559;',
       'boxV' => '&#x02551;',
       'boxVH' => '&#x0256C;',
       'boxVL' => '&#x02563;',
       'boxVR' => '&#x02560;',
       'boxVh' => '&#x0256B;',
       'boxVl' => '&#x02562;',
       'boxVr' => '&#x0255F;',
       'boxbox' => '&#x029C9;',
       'boxdL' => '&#x02555;',
       'boxdR' => '&#x02552;',
       'boxdl' => '&#x02510;',
       'boxdr' => '&#x0250C;',
       'boxh' => '&#x02500;',
       'boxhD' => '&#x02565;',
       'boxhU' => '&#x02568;',
       'boxhd' => '&#x0252C;',
       'boxhu' => '&#x02534;',
       'boxminus' => '&#x0229F;',
       'boxplus' => '&#x0229E;',
       'boxtimes' => '&#x022A0;',
       'boxuL' => '&#x0255B;',
       'boxuR' => '&#x02558;',
       'boxul' => '&#x02518;',
       'boxur' => '&#x02514;',
       'boxv' => '&#x02502;',
       'boxvH' => '&#x0256A;',
       'boxvL' => '&#x02561;',
       'boxvR' => '&#x0255E;',
       'boxvh' => '&#x0253C;',
       'boxvl' => '&#x02524;',
       'boxvr' => '&#x0251C;',
       'bprime' => '&#x02035;',
       'breve' => '&#x002D8;',
       'brvbar' => '&#166;',
       'bscr' => '&#x1D4B7;',
       'bsemi' => '&#x0204F;',
       'bsim' => '&#x0223D;',
       'bsime' => '&#x022CD;',
       'bsol' => '&#x0005C;',
       'bsolb' => '&#x029C5;',
       'bsolhsub' => '&#x0005C;&#x02282;',
       'bull' => '&#8226;',
       'bullet' => '&#x02022;',
       'bump' => '&#x0224E;',
       'bumpE' => '&#x02AAE;',
       'bumpe' => '&#x0224F;',
       'bumpeq' => '&#x0224F;',
       'cacute' => '&#x00107;',
       'cap' => '&#8745;',
       'capand' => '&#x02A44;',
       'capbrcup' => '&#x02A49;',
       'capcap' => '&#x02A4B;',
       'capcup' => '&#x02A47;',
       'capdot' => '&#x02A40;',
       'caps' => '&#x02229;&#x0FE00;',
       'caret' => '&#x02041;',
       'caron' => '&#x002C7;',
       'ccaps' => '&#x02A4D;',
       'ccaron' => '&#x0010D;',
       'ccedil' => '&#231;',
       'ccirc' => '&#x00109;',
       'ccups' => '&#x02A4C;',
       'ccupssm' => '&#x02A50;',
       'cdot' => '&#x0010B;',
       'cedil' => '&#184;',
       'cemptyv' => '&#x029B2;',
       'cent' => '&#162;',
       'centerdot' => '&#x000B7;',
       'cfr' => '&#x1D520;',
       'chcy' => '&#x00447;',
       'check' => '&#x02713;',
       'checkmark' => '&#x02713;',
       'chi' => '&#967;',
       'cir' => '&#x025CB;',
       'cirE' => '&#x029C3;',
       'circ' => '&#710;',
       'circeq' => '&#x02257;',
       'circlearrowleft' => '&#x021BA;',
       'circlearrowright' => '&#x021BB;',
       'circledR' => '&#x000AE;',
       'circledS' => '&#x024C8;',
       'circledast' => '&#x0229B;',
       'circledcirc' => '&#x0229A;',
       'circleddash' => '&#x0229D;',
       'cire' => '&#x02257;',
       'cirfnint' => '&#x02A10;',
       'cirmid' => '&#x02AEF;',
       'cirscir' => '&#x029C2;',
       'clubs' => '&#9827;',
       'clubsuit' => '&#x02663;',
       'colon' => '&#x0003A;',
       'colone' => '&#x02254;',
       'coloneq' => '&#x02254;',
       'comma' => '&#x0002C;',
       'commat' => '&#x00040;',
       'comp' => '&#x02201;',
       'compfn' => '&#x02218;',
       'complement' => '&#x02201;',
       'complexes' => '&#x02102;',
       'cong' => '&#8773;',
       'congdot' => '&#x02A6D;',
       'conint' => '&#x0222E;',
       'copf' => '&#x1D554;',
       'coprod' => '&#x02210;',
       'copy' => '&#169;',
       'copysr' => '&#x02117;',
       'crarr' => '&#8629;',
       'cross' => '&#x02717;',
       'cscr' => '&#x1D4B8;',
       'csub' => '&#x02ACF;',
       'csube' => '&#x02AD1;',
       'csup' => '&#x02AD0;',
       'csupe' => '&#x02AD2;',
       'ctdot' => '&#x022EF;',
       'cudarrl' => '&#x02938;',
       'cudarrr' => '&#x02935;',
       'cuepr' => '&#x022DE;',
       'cuesc' => '&#x022DF;',
       'cularr' => '&#x021B6;',
       'cularrp' => '&#x0293D;',
       'cup' => '&#8746;',
       'cupbrcap' => '&#x02A48;',
       'cupcap' => '&#x02A46;',
       'cupcup' => '&#x02A4A;',
       'cupdot' => '&#x0228D;',
       'cupor' => '&#x02A45;',
       'cups' => '&#x0222A;&#x0FE00;',
       'curarr' => '&#x021B7;',
       'curarrm' => '&#x0293C;',
       'curlyeqprec' => '&#x022DE;',
       'curlyeqsucc' => '&#x022DF;',
       'curlyvee' => '&#x022CE;',
       'curlywedge' => '&#x022CF;',
       'curren' => '&#164;',
       'curvearrowleft' => '&#x021B6;',
       'curvearrowright' => '&#x021B7;',
       'cuvee' => '&#x022CE;',
       'cuwed' => '&#x022CF;',
       'cwconint' => '&#x02232;',
       'cwint' => '&#x02231;',
       'cylcty' => '&#x0232D;',
       'dArr' => '&#8659;',
       'dHar' => '&#x02965;',
       'dagger' => '&#8224;',
       'daleth' => '&#x02138;',
       'darr' => '&#8595;',
       'dash' => '&#x02010;',
       'dashv' => '&#x022A3;',
       'dbkarow' => '&#x0290F;',
       'dblac' => '&#x002DD;',
       'dcaron' => '&#x0010F;',
       'dcy' => '&#x00434;',
       'dd' => '&#x02146;',
       'ddagger' => '&#x02021;',
       'ddarr' => '&#x021CA;',
       'ddotseq' => '&#x02A77;',
       'deg' => '&#176;',
       'delta' => '&#948;',
       'demptyv' => '&#x029B1;',
       'dfisht' => '&#x0297F;',
       'dfr' => '&#x1D521;',
       'dharl' => '&#x021C3;',
       'dharr' => '&#x021C2;',
       'diam' => '&#x022C4;',
       'diamond' => '&#x022C4;',
       'diamondsuit' => '&#x02666;',
       'diams' => '&#9830;',
       'die' => '&#x000A8;',
       'digamma' => '&#x003DC;',
       'disin' => '&#x022F2;',
       'div' => '&#x000F7;',
       'divide' => '&#247;',
       'divideontimes' => '&#x022C7;',
       'divonx' => '&#x022C7;',
       'djcy' => '&#x00452;',
       'dlcorn' => '&#x0231E;',
       'dlcrop' => '&#x0230D;',
       'dollar' => '&#x00024;',
       'dopf' => '&#x1D555;',
       'dot' => '&#x002D9;',
       'doteq' => '&#x02250;',
       'doteqdot' => '&#x02251;',
       'dotminus' => '&#x02238;',
       'dotplus' => '&#x02214;',
       'dotsquare' => '&#x022A1;',
       'doublebarwedge' => '&#x02306;',
       'downarrow' => '&#x02193;',
       'downdownarrows' => '&#x021CA;',
       'downharpoonleft' => '&#x021C3;',
       'downharpoonright' => '&#x021C2;',
       'drbkarow' => '&#x02910;',
       'drcorn' => '&#x0231F;',
       'drcrop' => '&#x0230C;',
       'dscr' => '&#x1D4B9;',
       'dscy' => '&#x00455;',
       'dsol' => '&#x029F6;',
       'dstrok' => '&#x00111;',
       'dtdot' => '&#x022F1;',
       'dtri' => '&#x025BF;',
       'dtrif' => '&#x025BE;',
       'duarr' => '&#x021F5;',
       'duhar' => '&#x0296F;',
       'dwangle' => '&#x029A6;',
       'dzcy' => '&#x0045F;',
       'dzigrarr' => '&#x0F5A2;',
       'eDDot' => '&#x02A77;',
       'eDot' => '&#x02251;',
       'eacute' => '&#233;',
       'easter' => '&#x0225B;',
       'ecaron' => '&#x0011B;',
       'ecir' => '&#x02256;',
       'ecirc' => '&#234;',
       'ecolon' => '&#x02255;',
       'ecy' => '&#x0044D;',
       'edot' => '&#x00117;',
       'ee' => '&#x02147;',
       'efDot' => '&#x02252;',
       'efr' => '&#x1D522;',
       'eg' => '&#x02A9A;',
       'egrave' => '&#232;',
       'egs' => '&#x022DD;',
       'egsdot' => '&#x02A98;',
       'el' => '&#x02A99;',
       'ell' => '&#x02113;',
       'els' => '&#x022DC;',
       'elsdot' => '&#x02A97;',
       'emacr' => '&#x00113;',
       'empty' => '&#8709;',
       'emptyset' => '&#x02205;&#x0FE00;',
       'emptyv' => '&#x02205;',
       'emsp' => '&#8195;',
       'emsp13' => '&#x02004;',
       'emsp14' => '&#x02005;',
       'eng' => '&#x0014B;',
       'ensp' => '&#8194;',
       'eogon' => '&#x00119;',
       'eopf' => '&#x1D556;',
       'epar' => '&#x022D5;',
       'eparsl' => '&#x029E3;',
       'eplus' => '&#x02A71;',
       'epsi' => '&#x003B5;',
       'epsilon' => '&#949;',
       'epsiv' => '&#x0025B;',
       'eqcirc' => '&#x02256;',
       'eqcolon' => '&#x02255;',
       'eqsim' => '&#x02242;',
       'eqslantgtr' => '&#x022DD;',
       'eqslantless' => '&#x022DC;',
       'equals' => '&#x0003D;',
       'equest' => '&#x0225F;',
       'equiv' => '&#8801;',
       'equivDD' => '&#x02A78;',
       'eqvparsl' => '&#x029E5;',
       'erDot' => '&#x02253;',
       'erarr' => '&#x02971;',
       'escr' => '&#x0212F;',
       'esdot' => '&#x02250;',
       'esim' => '&#x02242;',
       'eta' => '&#951;',
       'eth' => '&#240;',
       'euml' => '&#235;',
       'euro' => '&#8364;',
       'excl' => '&#x00021;',
       'exist' => '&#8707;',
       'expectation' => '&#x02130;',
       'exponentiale' => '&#x02147;',
       'fallingdotseq' => '&#x02252;',
       'fcy' => '&#x00444;',
       'female' => '&#x02640;',
       'ffilig' => '&#x0FB03;',
       'fflig' => '&#x0FB00;',
       'ffllig' => '&#x0FB04;',
       'ffr' => '&#x1D523;',
       'filig' => '&#x0FB01;',
       'flat' => '&#x0266D;',
       'fllig' => '&#x0FB02;',
       'fnof' => '&#402;',
       'fopf' => '&#x1D557;',
       'forall' => '&#8704;',
       'fork' => '&#x022D4;',
       'forkv' => '&#x02AD9;',
       'fpartint' => '&#x02A0D;',
       'frac12' => '&#189;',
       'frac13' => '&#x02153;',
       'frac14' => '&#188;',
       'frac15' => '&#x02155;',
       'frac16' => '&#x02159;',
       'frac18' => '&#x0215B;',
       'frac23' => '&#x02154;',
       'frac25' => '&#x02156;',
       'frac34' => '&#190;',
       'frac35' => '&#x02157;',
       'frac38' => '&#x0215C;',
       'frac45' => '&#x02158;',
       'frac56' => '&#x0215A;',
       'frac58' => '&#x0215D;',
       'frac78' => '&#x0215E;',
       'frasl' => '&#8260;',
       'frown' => '&#x02322;',
       'fscr' => '&#x1D4BB;',
       'gE' => '&#x02267;',
       'gEl' => '&#x022DB;',
       'gacute' => '&#x001F5;',
       'gamma' => '&#947;',
       'gammad' => '&#x003DC;',
       'gap' => '&#x02273;',
       'gbreve' => '&#x0011F;',
       'gcirc' => '&#x0011D;',
       'gcy' => '&#x00433;',
       'gdot' => '&#x00121;',
       'ge' => '&#8805;',
       'gel' => '&#x022DB;',
       'geq' => '&#x02265;',
       'geqq' => '&#x02267;',
       'geqslant' => '&#x02A7E;',
       'ges' => '&#x02A7E;',
       'gescc' => '&#x02AA9;',
       'gesdot' => '&#x02A80;',
       'gesdoto' => '&#x02A82;',
       'gesdotol' => '&#x02A84;',
       'gesl' => '&#x022DB;&#x0FE00;',
       'gesles' => '&#x02A94;',
       'gfr' => '&#x1D524;',
       'gg' => '&#x0226B;',
       'ggg' => '&#x022D9;',
       'gimel' => '&#x02137;',
       'gjcy' => '&#x00453;',
       'gl' => '&#x02277;',
       'glE' => '&#x02A92;',
       'gla' => '&#x02AA5;',
       'glj' => '&#x02AA4;',
       'gnE' => '&#x02269;',
       'gnap' => '&#x02A8A;',
       'gnapprox' => '&#x02A8A;',
       'gne' => '&#x02269;',
       'gneq' => '&#x02269;',
       'gneqq' => '&#x02269;',
       'gnsim' => '&#x022E7;',
       'gopf' => '&#x1D558;',
       'grave' => '&#x00060;',
       'gscr' => '&#x0210A;',
       'gsim' => '&#x02273;',
       'gsime' => '&#x02A8E;',
       'gsiml' => '&#x02A90;',
       'gt' => '&#62;',
       'gtcc' => '&#x02AA7;',
       'gtcir' => '&#x02A7A;',
       'gtdot' => '&#x022D7;',
       'gtlPar' => '&#x02995;',
       'gtquest' => '&#x02A7C;',
       'gtrapprox' => '&#x02273;',
       'gtrarr' => '&#x02978;',
       'gtrdot' => '&#x022D7;',
       'gtreqless' => '&#x022DB;',
       'gtreqqless' => '&#x022DB;',
       'gtrless' => '&#x02277;',
       'gtrsim' => '&#x02273;',
       'gvertneqq' => '&#x02269;&#x0FE00;',
       'gvnE' => '&#x02269;&#x0FE00;',
       'hArr' => '&#8660;',
       'hairsp' => '&#x0200A;',
       'half' => '&#x000BD;',
       'hamilt' => '&#x0210B;',
       'hardcy' => '&#x0044A;',
       'harr' => '&#8596;',
       'harrcir' => '&#x02948;',
       'harrw' => '&#x021AD;',
       'hbar' => '&#x0210F;',       # Render Problem, hslash instead  (not working -> '&#x0210E;&#x00305;')
       'dbar' => '&#100;&#x00305;', # Render Problem, dbar  not working -> '&#100;&#x00305;')
       'hcirc' => '&#x00125;',      # Diacritical marks don't work the way they should in mozilla
       'hearts' => '&#9829;',
       'heartsuit' => '&#x02661;',
       'hellip' => '&#8230;',
       'hercon' => '&#x022B9;',
       'hfr' => '&#x1D525;',
       'hksearow' => '&#x02925;',
       'hkswarow' => '&#x02926;',
       'hoarr' => '&#x021FF;',
       'homtht' => '&#x0223B;',
       'hookleftarrow' => '&#x021A9;',
       'hookrightarrow' => '&#x021AA;',
       'hopf' => '&#x1D559;',
       'horbar' => '&#x02015;',
       'hscr' => '&#x1D4BD;',
       'hslash' => '&#x0210F;',
       'hstrok' => '&#x00127;',
       'hybull' => '&#x02043;',
       'hyphen' => '&#x02010;',
       'iacute' => '&#237;',
       'ic' => '&#x0200B;',
       'icirc' => '&#238;',
       'icy' => '&#x00438;',
       'iecy' => '&#x00435;',
       'iexcl' => '&#161;',
       'iff' => '&#x021D4;',
       'ifr' => '&#x1D526;',
       'igrave' => '&#236;',
       'ii' => '&#x02148;',
       'iiiint' => '&#x02A0C;',
       'iiint' => '&#x0222D;',
       'iinfin' => '&#x029DC;',
       'iiota' => '&#x02129;',
       'ijlig' => '&#x00133;',
       'imacr' => '&#x0012B;',
       'image' => '&#8465;',
       'imagline' => '&#x02110;',
       'imagpart' => '&#x02111;',
       'imath' => '&#x00131;',
       'imof' => '&#x022B7;',
       'imped' => '&#x1D543;',
       'in' => '&#x02208;',
       'incare' => '&#x02105;',
       'infin' => '&#8734;',
       'inodot' => '&#x00131;',
       'int' => '&#8747;',
       'intcal' => '&#x022BA;',
       'integers' => '&#x02124;',
       'intercal' => '&#x022BA;',
       'intlarhk' => '&#x02A17;',
       'intprod' => '&#x02A3C;',
       'iocy' => '&#x00451;',
       'iogon' => '&#x0012F;',
       'iopf' => '&#x1D55A;',
       'iota' => '&#953;',
       'iprod' => '&#x02A3C;',
       'iquest' => '&#191;',
       'iscr' => '&#x1D4BE;',
       'isin' => '&#8712;',
       'isinE' => '&#x022F9;',
       'isindot' => '&#x022F5;',
       'isins' => '&#x022F4;',
       'isinsv' => '&#x022F3;',
       'isinv' => '&#x02208;',
       'it' => '&#x02062;',
       'itilde' => '&#x00129;',
       'iukcy' => '&#x00456;',
       'iuml' => '&#239;',
       'jcirc' => '&#x00135;',
       'jcy' => '&#x00439;',
       'jfr' => '&#x1D527;',
       'jmath' => '&#x0006A;&#x0FE00;',
       'jopf' => '&#x1D55B;',
       'jscr' => '&#x1D4BF;',
       'jsercy' => '&#x00458;',
       'jukcy' => '&#x00454;',
       'kappa' => '&#954;',
       'kappav' => '&#x003F0;',
       'kcedil' => '&#x00137;',
       'kcy' => '&#x0043A;',
       'kfr' => '&#x1D528;',
       'kgreen' => '&#x00138;',
       'khcy' => '&#x00445;',
       'kjcy' => '&#x0045C;',
       'kopf' => '&#x1D55C;',
       'kscr' => '&#x1D4C0;',
       'lAarr' => '&#x021DA;',
       'lArr' => '&#8656;',
       'lAtail' => '&#x0291B;',
       'lBarr' => '&#x0290E;',
       'lE' => '&#x02266;',
       'lEg' => '&#x022DA;',
       'lHar' => '&#x02962;',
       'lacute' => '&#x0013A;',
       'laemptyv' => '&#x029B4;',
       'lagran' => '&#x02112;',
       'lambda' => '&#955;',
       'lang' => '&#9001;',
       'langd' => '&#x02991;',
       'langle' => '&#x02329;',
       'lap' => '&#x02272;',
       'laquo' => '&#171;',
       'larr' => '&#8592;',
       'larrb' => '&#x021E4;',
       'larrbfs' => '&#x0291F;',
       'larrfs' => '&#x0291D;',
       'larrhk' => '&#x021A9;',
       'larrlp' => '&#x021AB;',
       'larrpl' => '&#x02939;',
       'larrsim' => '&#x02973;',
       'larrtl' => '&#x021A2;',
       'lat' => '&#x02AAB;',
       'latail' => '&#x02919;',
       'late' => '&#x02AAD;',
       'lates' => '&#x02AAD;&#x0FE00;',
       'lbarr' => '&#x0290C;',
       'lbbrk' => '&#x03014;',
       'lbrace' => '&#x0007B;',
       'lbrack' => '&#x0005B;',
       'lbrke' => '&#x0298B;',
       'lbrksld' => '&#x0298F;',
       'lbrkslu' => '&#x0298D;',
       'lcaron' => '&#x0013E;',
       'lcedil' => '&#x0013C;',
       'lceil' => '&#8968;',
       'lcub' => '&#x0007B;',
       'lcy' => '&#x0043B;',
       'ldca' => '&#x02936;',
       'ldquo' => '&#8220;',
       'ldquor' => '&#x0201E;',
       'ldrdhar' => '&#x02967;',
       'ldrushar' => '&#x0294B;',
       'ldsh' => '&#x021B2;',
       'le' => '&#8804;',
       'leftarrow' => '&#x02190;',
       'leftarrowtail' => '&#x021A2;',
       'leftharpoondown' => '&#x021BD;',
       'leftharpoonup' => '&#x021BC;',
       'leftleftarrows' => '&#x021C7;',
       'leftrightarrow' => '&#x02194;',
       'leftrightarrows' => '&#x021C6;',
       'leftrightharpoons' => '&#x021CB;',
       'leftrightsquigarrow' => '&#x021AD;',
       'leftthreetimes' => '&#x022CB;',
       'leg' => '&#x022DA;',
       'leq' => '&#x02264;',
       'leqq' => '&#x02266;',
       'leqslant' => '&#x02A7D;',
       'les' => '&#x02A7D;',
       'lescc' => '&#x02AA8;',
       'lesdot' => '&#x02A7F;',
       'lesdoto' => '&#x02A81;',
       'lesdotor' => '&#x02A83;',
       'lesg' => '&#x022DA;&#x0FE00;',
       'lesges' => '&#x02A93;',
       'lessapprox' => '&#x02272;',
       'lessdot' => '&#x022D6;',
       'lesseqgtr' => '&#x022DA;',
       'lesseqqgtr' => '&#x022DA;',
       'lessgtr' => '&#x02276;',
       'lesssim' => '&#x02272;',
       'lfisht' => '&#x0297C;',
       'lfloor' => '&#8970;',
       'lfr' => '&#x1D529;',
       'lg' => '&#x02276;',
       'lgE' => '&#x02A91;',
       'lhard' => '&#x021BD;',
       'lharu' => '&#x021BC;',
       'lharul' => '&#x0296A;',
       'lhblk' => '&#x02584;',
       'ljcy' => '&#x00459;',
       'll' => '&#x0226A;',
       'llarr' => '&#x021C7;',
       'llcorner' => '&#x0231E;',
       'llhard' => '&#x0296B;',
       'lltri' => '&#x025FA;',
       'lmidot' => '&#x00140;',
       'lmoust' => '&#x023B0;',
       'lmoustache' => '&#x023B0;',
       'lnE' => '&#x02268;',
       'lnap' => '&#x02A89;',
       'lnapprox' => '&#x02A89;',
       'lne' => '&#x02268;',
       'lneq' => '&#x02268;',
       'lneqq' => '&#x02268;',
       'lnsim' => '&#x022E6;',
       'loang' => '&#x0F558;',
       'loarr' => '&#x021FD;',
       'lobrk' => '&#x0301A;',
       'longleftarrow' => '&#x0F576;',
       'longleftrightarrow' => '&#x0F578;',
       'longmapsto' => '&#x0F57D;',
       'longrightarrow' => '&#x0F577;',
       'looparrowleft' => '&#x021AB;',
       'looparrowright' => '&#x021AC;',
       'lopar' => '&#x03018;',
       'lopf' => '&#x1D55D;',
       'loplus' => '&#x02A2D;',
       'lotimes' => '&#x02A34;',
       'lowast' => '&#8727;',
       'lowbar' => '&#x0005F;',
       'loz' => '&#9674;',
       'lozenge' => '&#x025CA;',
       'lozf' => '&#x029EB;',
       'lpar' => '&#x00028;',
       'lparlt' => '&#x02993;',
       'lrarr' => '&#x021C6;',
       'lrcorner' => '&#x0231F;',
       'lrhar' => '&#x021CB;',
       'lrhard' => '&#x0296D;',
       'lrm' => '&#8206;',
       'lrtri' => '&#x022BF;',
       'lsaquo' => '&#8249;',
       'lscr' => '&#x02113;',
       'lsh' => '&#x021B0;',
       'lsim' => '&#x02272;',
       'lsime' => '&#x02A8D;',
       'lsimg' => '&#x02A8F;',
       'lsqb' => '&#x0005B;',
       'lsquo' => '&#8216;',
       'lsquor' => '&#x0201A;',
       'lstrok' => '&#x00142;',
       'lt' => '&#60;',
       'ltcc' => '&#x02AA6;',
       'ltcir' => '&#x02A79;',
       'ltdot' => '&#x022D6;',
       'lthree' => '&#x022CB;',
       'ltimes' => '&#x022C9;',
       'ltlarr' => '&#x02976;',
       'ltquest' => '&#x02A7B;',
       'ltrPar' => '&#x02996;',
       'ltri' => '&#x025C3;',
       'ltrie' => '&#x022B4;',
       'ltrif' => '&#x025C2;',
       'lurdshar' => '&#x0294A;',
       'luruhar' => '&#x02966;',
       'lvertneqq' => '&#x02268;&#x0FE00;',
       'lvnE' => '&#x02268;&#x0FE00;',
       'mDDot' => '&#x0223A;',
       'macr' => '&#175;',
       'male' => '&#x02642;',
       'malt' => '&#x02720;',
       'maltese' => '&#x02720;',
       'map' => '&#x021A6;',
       'mapsto' => '&#x021A6;',
       'mapstodown' => '&#x021A7;',
       'mapstoleft' => '&#x021A4;',
       'mapstoup' => '&#x021A5;',
       'marker' => '&#x025AE;',
       'mcomma' => '&#x02A29;',
       'mcy' => '&#x0043C;',
       'mdash' => '&#8212;',
       'measuredangle' => '&#x02221;',
       'mfr' => '&#x1D52A;',
       'mho' => '&#x02127;',
       'micro' => '&#181;',
       'mid' => '&#x02223;',
       'midast' => '&#x0002A;',
       'midcir' => '&#x02AF0;',
       'middot' => '&#183;',
       'minus' => '&#8722;',
       'minusb' => '&#x0229F;',
       'minusd' => '&#x02238;',
       'minusdu' => '&#x02A2A;',
       'mlcp' => '&#x02ADB;',
       'mldr' => '&#x02026;',
       'mnplus' => '&#x02213;',
       'models' => '&#x022A7;',
       'mopf' => '&#x1D55E;',
       'mp' => '&#x02213;',
       'mscr' => '&#x1D4C2;',
       'mstpos' => '&#x0223E;',
       'mu' => '&#956;',
       'multimap' => '&#x022B8;',
       'mumap' => '&#x022B8;',
       'nGg' => '&#x022D9;&#x00338;',
       'nGt' => '&#x0226B;&#x00338;',
       'nGtv' => '&#x0226B;&#x00338;&#x0FE00;',
       'nLeftarrow' => '&#x021CD;',
       'nLeftrightarrow' => '&#x021CE;',
       'nLl' => '&#x022D8;&#x00338;',
       'nLt' => '&#x0226A;&#x00338;',
       'nLtv' => '&#x0226A;&#x00338;&#x0FE00;',
       'nRightarrow' => '&#x021CF;',
       'nVDash' => '&#x022AF;',
       'nVdash' => '&#x022AE;',
       'nabla' => '&#8711;',
       'nacute' => '&#x00144;',
       'nang' => '&#x02220;&#x00338;',
       'nap' => '&#x02249;',
       'napE' => '&#x02A70;&#x00338;',
       'napid' => '&#x0224B;&#x00338;',
       'napos' => '&#x00149;',
       'napprox' => '&#x02249;',
       'natur' => '&#x0266E;',
       'natural' => '&#x0266E;',
       'naturals' => '&#x02115;',
       'nbsp' => '&#160;',
       'nbump' => '&#x0224E;&#x00338;',
       'nbumpe' => '&#x0224F;&#x00338;',
       'ncap' => '&#x02A43;',
       'ncaron' => '&#x00148;',
       'ncedil' => '&#x00146;',
       'ncong' => '&#x02247;',
       'ncongdot' => '&#x02A6D;&#x00338;',
       'ncup' => '&#x02A42;',
       'ncy' => '&#x0043D;',
       'ndash' => '&#8211;',
       'ne' => '&#8800;',
       'neArr' => '&#x021D7;',
       'nearhk' => '&#x02924;',
       'nearr' => '&#x02197;',
       'nearrow' => '&#x02197;',
       'nedot' => '&#x02260;&#x0FE00;',
       'nequiv' => '&#x02262;',
       'nesear' => '&#x02928;',
       'nesim' => '&#x02242;&#x00338;',
       'nexist' => '&#x02204;',
       'nexists' => '&#x02204;',
       'nfr' => '&#x1D52B;',
       'ngE' => '&#x02271;',
       'nge' => '&#x02271;&#x020E5;',
       'ngeq' => '&#x02271;&#x020E5;',
       'ngeqq' => '&#x02271;',
       'ngeqslant' => '&#x02271;',
       'nges' => '&#x02271;',
       'ngsim' => '&#x02275;',
       'ngt' => '&#x0226F;',
       'ngtr' => '&#x0226F;',
       'nhArr' => '&#x021CE;',
       'nharr' => '&#x021AE;',
       'nhpar' => '&#x02AF2;',
       'ni' => '&#8715;',
       'nis' => '&#x022FC;',
       'nisd' => '&#x022FA;',
       'niv' => '&#x0220B;',
       'njcy' => '&#x0045A;',
       'nlArr' => '&#x021CD;',
       'nlE' => '&#x02270;',
       'nlarr' => '&#x0219A;',
       'nldr' => '&#x02025;',
       'nle' => '&#x02270;&#x020E5;',
       'nleftarrow' => '&#x0219A;',
       'nleftrightarrow' => '&#x021AE;',
       'nleq' => '&#x02270;&#x020E5;',
       'nleqq' => '&#x02270;',
       'nleqslant' => '&#x02270;',
       'nles' => '&#x02270;',
       'nless' => '&#x0226E;',
       'nlsim' => '&#x02274;',
       'nlt' => '&#x0226E;',
       'nltri' => '&#x022EA;',
       'nltrie' => '&#x022EC;',
       'nmid' => '&#x02224;',
       'nopf' => '&#x1D55F;',
       'not' => '&#172;',
       'notin' => '&#8713;',
       'notindot' => '&#x022F6;&#x0FE00;',
       'notinva' => '&#x02209;&#x00338;',
       'notinvb' => '&#x022F7;',
       'notinvc' => '&#x022F6;',
       'notni' => '&#x0220C;',
       'notniva' => '&#x0220C;',
       'notnivb' => '&#x022FE;',
       'notnivc' => '&#x022FD;',
       'npar' => '&#x02226;',
       'nparallel' => '&#x02226;',
       'nparsl' => '&#x02225;&#x0FE00;&#x020E5;',
       'npart' => '&#x02202;&#x00338;',
       'npolint' => '&#x02A14;',
       'npr' => '&#x02280;',
       'nprcue' => '&#x022E0;',
       'npre' => '&#x02AAF;&#x00338;',
       'nprec' => '&#x02280;',
       'npreceq' => '&#x02AAF;&#x00338;',
       'nrArr' => '&#x021CF;',
       'nrarr' => '&#x0219B;',
       'nrarrc' => '&#x02933;&#x00338;',
       'nrarrw' => '&#x0219D;&#x00338;',
       'nrightarrow' => '&#x0219B;',
       'nrtri' => '&#x022EB;',
       'nrtrie' => '&#x022ED;',
       'nsc' => '&#x02281;',
       'nsccue' => '&#x022E1;',
       'nsce' => '&#x02AB0;&#x00338;',
       'nscr' => '&#x1D4C3;',
       'nshortmid' => '&#x02224;&#x0FE00;',
       'nshortparallel' => '&#x02226;&#x0FE00;',
       'nsim' => '&#x02241;',
       'nsime' => '&#x02244;',
       'nsimeq' => '&#x02244;',
       'nsmid' => '&#x02224;&#x0FE00;',
       'nspar' => '&#x02226;&#x0FE00;',
       'nsqsube' => '&#x022E2;',
       'nsqsupe' => '&#x022E3;',
       'nsub' => '&#8836;',
       'nsubE' => '&#x02288;',
       'nsube' => '&#x02288;',
       'nsubset' => '&#x02284;',
       'nsubseteq' => '&#x02288;',
       'nsubseteqq' => '&#x02288;',
       'nsucc' => '&#x02281;',
       'nsucceq' => '&#x02AB0;&#x00338;',
       'nsup' => '&#x02285;',
       'nsupE' => '&#x02289;',
       'nsupe' => '&#x02289;',
       'nsupset' => '&#x02285;',
       'nsupseteq' => '&#x02289;',
       'nsupseteqq' => '&#x02289;',
       'ntgl' => '&#x02279;',
       'ntilde' => '&#241;',
       'ntlg' => '&#x02278;',
       'ntriangleleft' => '&#x022EA;',
       'ntrianglelefteq' => '&#x022EC;',
       'ntriangleright' => '&#x022EB;',
       'ntrianglerighteq' => '&#x022ED;',
       'nu' => '&#957;',
       'num' => '&#x00023;',
       'numero' => '&#x02116;',
       'numsp' => '&#x02007;',
       'nvDash' => '&#x022AD;',
       'nvHarr' => '&#x021CE;',
       'nvap' => '&#x02249;&#x00338;',
       'nvdash' => '&#x022AC;',
       'nvge' => '&#x02271;',
       'nvgt' => '&#x0226F;',
       'nvinfin' => '&#x029DE;',
       'nvlArr' => '&#x021CD;',
       'nvle' => '&#x02270;',
       'nvlt' => '&#x0226E;',
       'nvltrie' => '&#x022EC;&#x00338;',
       'nvrArr' => '&#x021CF;',
       'nvrtrie' => '&#x022ED;&#x00338;',
       'nvsim' => '&#x02241;&#x00338;',
       'nwArr' => '&#x021D6;',
       'nwarhk' => '&#x02923;',
       'nwarr' => '&#x02196;',
       'nwarrow' => '&#x02196;',
       'nwnear' => '&#x02927;',
       'oS' => '&#x024C8;',
       'oacute' => '&#243;',
       'oast' => '&#x0229B;',
       'ocir' => '&#x0229A;',
       'ocirc' => '&#244;',
       'ocy' => '&#x0043E;',
       'odash' => '&#x0229D;',
       'odblac' => '&#x00151;',
       'odiv' => '&#x02A38;',
       'odot' => '&#x02299;',
       'odsold' => '&#x029BC;',
       'oelig' => '&#339;',
       'ofcir' => '&#x029BF;',
       'ofr' => '&#x1D52C;',
       'ogon' => '&#x002DB;',
       'ograve' => '&#242;',
       'ogt' => '&#x029C1;',
       'ohbar' => '&#x029B5;',
       'ohm' => '&#x02126;',
       'oint' => '&#x0222E;',
       'olarr' => '&#x021BA;',
       'olcir' => '&#x029BE;',
       'olcross' => '&#x029BB;',
       'oline' => '&#8254;',
       'olt' => '&#x029C0;',
       'omacr' => '&#x0014D;',
       'omega' => '&#969;',
       'omicron' => '&#959;',
       'omid' => '&#x029B6;',
       'ominus' => '&#x02296;',
       'oopf' => '&#x1D560;',
       'opar' => '&#x029B7;',
       'operp' => '&#x029B9;',
       'oplus' => '&#8853;',
       'or' => '&#8744;',
       'orarr' => '&#x021BB;',
       'ord' => '&#x02A5D;',
       'order' => '&#x02134;',
       'orderof' => '&#x02134;',
       'ordf' => '&#170;',
       'ordm' => '&#186;',
       'origof' => '&#x022B6;',
       'oror' => '&#x02A56;',
       'orslope' => '&#x02A57;',
       'orv' => '&#x02A5B;',
       'oscr' => '&#x02134;',
       'oslash' => '&#248;',
       'osol' => '&#x02298;',
       'otilde' => '&#245;',
       'otimes' => '&#8855;',
       'otimesas' => '&#x02A36;',
       'ouml' => '&#246;',
       'ovbar' => '&#x0233D;',
       'par' => '&#x02225;',
       'para' => '&#182;',
       'parallel' => '&#x02225;',
       'parsim' => '&#x02AF3;',
       'parsl' => '&#x02225;&#x0FE00;',
       'part' => '&#8706;',
       'pcy' => '&#x0043F;',
       'percnt' => '&#x00025;',
       'period' => '&#x0002E;',
       'permil' => '&#8240;',
       'perp' => '&#8869;',
       'pertenk' => '&#x02031;',
       'pfr' => '&#x1D52D;',
       'phi' => '&#966;',
       'phiv' => '&#x003D5;',
       'phmmat' => '&#x02133;',
       'phone' => '&#x0260E;',
       'pi' => '&#960;',
       'pitchfork' => '&#x022D4;',
       'piv' => '&#982;',
       'planck' => '&#x0210F;&#x0FE00;',
       'planckh' => '&#x0210E;',
       'plankv' => '&#x0210F;',
       'plus' => '&#x0002B;',
       'plusacir' => '&#x02A23;',
       'plusb' => '&#x0229E;',
       'pluscir' => '&#x02A22;',
       'plusdo' => '&#x02214;',
       'plusdu' => '&#x02A25;',
       'pluse' => '&#x02A72;',
       'plusmn' => '&#177;',
       'plussim' => '&#x02A26;',
       'plustwo' => '&#x02A27;',
       'pm' => '&#x000B1;',
       'pointint' => '&#x02A15;',
       'popf' => '&#x1D561;',
       'pound' => '&#163;',
       'pr' => '&#x0227A;',
       'prE' => '&#x02AAF;',
       'prap' => '&#x0227E;',
       'prcue' => '&#x0227C;',
       'pre' => '&#x02AAF;',
       'prec' => '&#x0227A;',
       'precapprox' => '&#x0227E;',
       'preccurlyeq' => '&#x0227C;',
       'preceq' => '&#x02AAF;',
       'precnapprox' => '&#x022E8;',
       'precneqq' => '&#x02AB5;',
       'precnsim' => '&#x022E8;',
       'precsim' => '&#x0227E;',
       'prime' => '&#8242;',
       'primes' => '&#x02119;',
       'prnE' => '&#x02AB5;',
       'prnap' => '&#x022E8;',
       'prnsim' => '&#x022E8;',
       'prod' => '&#8719;',
       'profalar' => '&#x0232E;',
       'profline' => '&#x02312;',
       'profsurf' => '&#x02313;',
       'prop' => '&#8733;',
       'propto' => '&#x0221D;',
       'prsim' => '&#x0227E;',
       'prurel' => '&#x022B0;',
       'pscr' => '&#x1D4C5;',
       'psi' => '&#968;',
       'puncsp' => '&#x02008;',
       'qfr' => '&#x1D52E;',
       'qint' => '&#x02A0C;',
       'qopf' => '&#x1D562;',
       'qprime' => '&#x02057;',
       'qscr' => '&#x1D4C6;',
       'quaternions' => '&#x0210D;',
       'quatint' => '&#x02A16;',
       'quest' => '&#x0003F;',
       'questeq' => '&#x0225F;',
       'quot' => '&#34;',
       'rAarr' => '&#x021DB;',
       'rArr' => '&#8658;',
       'rAtail' => '&#x0291C;',
       'rBarr' => '&#x0290F;',
       'rHar' => '&#x02964;',
       'race' => '&#x029DA;',
       'racute' => '&#x00155;',
       'radic' => '&#8730;',
       'raemptyv' => '&#x029B3;',
       'rang' => '&#9002;',
       'rangd' => '&#x02992;',
       'range' => '&#x029A5;',
       'rangle' => '&#x0232A;',
       'raquo' => '&#187;',
       'rarr' => '&#8594;',
       'rarrap' => '&#x02975;',
       'rarrb' => '&#x021E5;',
       'rarrbfs' => '&#x02920;',
       'rarrc' => '&#x02933;',
       'rarrfs' => '&#x0291E;',
       'rarrhk' => '&#x021AA;',
       'rarrlp' => '&#x021AC;',
       'rarrpl' => '&#x02945;',
       'rarrsim' => '&#x02974;',
       'rarrtl' => '&#x021A3;',
       'rarrw' => '&#x0219D;',
       'ratail' => '&#x021A3;',
       'ratio' => '&#x02236;',
       'rationals' => '&#x0211A;',
       'rbarr' => '&#x0290D;',
       'rbbrk' => '&#x03015;',
       'rbrace' => '&#x0007D;',
       'rbrack' => '&#x0005D;',
       'rbrke' => '&#x0298C;',
       'rbrksld' => '&#x0298E;',
       'rbrkslu' => '&#x02990;',
       'rcaron' => '&#x00159;',
       'rcedil' => '&#x00157;',
       'rceil' => '&#8969;',
       'rcub' => '&#x0007D;',
       'rcy' => '&#x00440;',
       'rdca' => '&#x02937;',
       'rdldhar' => '&#x02969;',
       'rdquo' => '&#8221;',
       'rdquor' => '&#x0201D;',
       'rdsh' => '&#x021B3;',
       'real' => '&#8476;',
       'realine' => '&#x0211B;',
       'realpart' => '&#x0211C;',
       'reals' => '&#x0211D;',
       'rect' => '&#x025AD;',
       'reg' => '&#174;',
       'rfisht' => '&#x0297D;',
       'rfloor' => '&#8971;',
       'rfr' => '&#x1D52F;',
       'rhard' => '&#x021C1;',
       'rharu' => '&#x021C0;',
       'rharul' => '&#x0296C;',
       'rho' => '&#961;',
       'rhov' => '&#x003F1;',
       'rightarrow' => '&#x02192;',
       'rightarrowtail' => '&#x021A3;',
       'rightharpoondown' => '&#x021C1;',
       'rightharpoonup' => '&#x021C0;',
       'rightleftarrows' => '&#x021C4;',
       'rightleftharpoons' => '&#x021CC;',
       'rightrightarrows' => '&#x021C9;',
       'rightsquigarrow' => '&#x0219D;',
       'rightthreetimes' => '&#x022CC;',
       'ring' => '&#x002DA;',
       'risingdotseq' => '&#x02253;',
       'rlarr' => '&#x021C4;',
       'rlhar' => '&#x021CC;',
       'rlm' => '&#8207;',
       'rmoust' => '&#x023B1;',
       'rmoustache' => '&#x023B1;',
       'rnmid' => '&#x02AEE;',
       'roang' => '&#x0F559;',
       'roarr' => '&#x021FE;',
       'robrk' => '&#x0301B;',
       'ropar' => '&#x03019;',
       'ropf' => '&#x1D563;',
       'roplus' => '&#x02A2E;',
       'rotimes' => '&#x02A35;',
       'rpar' => '&#x00029;',
       'rpargt' => '&#x02994;',
       'rppolint' => '&#x02A12;',
       'rrarr' => '&#x021C9;',
       'rsaquo' => '&#8250;',
       'rscr' => '&#x1D4C7;',
       'rsh' => '&#x021B1;',
       'rsqb' => '&#x0005D;',
       'rsquo' => '&#8217;',
       'rsquor' => '&#x02019;',
       'rthree' => '&#x022CC;',
       'rtimes' => '&#x022CA;',
       'rtri' => '&#x025B9;',
       'rtrie' => '&#x022B5;',
       'rtrif' => '&#x025B8;',
       'rtriltri' => '&#x029CE;',
       'ruluhar' => '&#x02968;',
       'rx' => '&#x0211E;',
       'sacute' => '&#x0015B;',
       'sbquo' => '&#8218;',
       'sc' => '&#x0227B;',
       'scE' => '&#x0227E;',
       'scap' => '&#x0227F;',
       'scaron' => '&#353;',
       'sccue' => '&#x0227D;',
       'sce' => '&#x0227D;',
       'scedil' => '&#x0015F;',
       'scirc' => '&#x0015D;',
       'scnE' => '&#x02AB6;',
       'scnap' => '&#x022E9;',
       'scnsim' => '&#x022E9;',
       'scpolint' => '&#x02A13;',
       'scsim' => '&#x0227F;',
       'scy' => '&#x00441;',
       'sdot' => '&#8901;',
       'sdotb' => '&#x022A1;',
       'sdote' => '&#x02A66;',
       'seArr' => '&#x021D8;',
       'searhk' => '&#x02925;',
       'searr' => '&#x02198;',
       'searrow' => '&#x02198;',
       'sect' => '&#167;',
       'semi' => '&#x0003B;',
       'seswar' => '&#x02929;',
       'setminus' => '&#x02216;',
       'setmn' => '&#x02216;',
       'sext' => '&#x02736;',
       'sfr' => '&#x1D530;',
       'sharp' => '&#x0266F;',
       'shchcy' => '&#x00449;',
       'shcy' => '&#x00448;',
       'shortmid' => '&#x02223;&#x0FE00;',
       'shortparallel' => '&#x02225;&#x0FE00;',
       'shy' => '&#173;',
       'sigma' => '&#963;',
       'sigmaf' => '&#962;',
       'sigmav' => '&#x003C2;',
       'sim' => '&#8764;',
       'simdot' => '&#x02A6A;',
       'sime' => '&#x02243;',
       'simeq' => '&#x02243;',
       'simg' => '&#x02A9E;',
       'simgE' => '&#x02AA0;',
       'siml' => '&#x02A9D;',
       'simlE' => '&#x02A9F;',
       'simne' => '&#x02246;',
       'simplus' => '&#x02A24;',
       'simrarr' => '&#x02972;',
       'slarr' => '&#x02190;&#x0FE00;',
       'smallsetminus' => '&#x02216;&#x0FE00;',
       'smashp' => '&#x02A33;',
       'smeparsl' => '&#x029E4;',
       'smid' => '&#x02223;&#x0FE00;',
       'smile' => '&#x02323;',
       'smt' => '&#x02AAA;',
       'smte' => '&#x02AAC;',
       'smtes' => '&#x02AAC;&#x0FE00;',
       'softcy' => '&#x0044C;',
       'sol' => '&#x0002F;',
       'solb' => '&#x029C4;',
       'solbar' => '&#x0233F;',
       'sopf' => '&#x1D564;',
       'spades' => '&#9824;',
       'spadesuit' => '&#x02660;',
       'spar' => '&#x02225;&#x0FE00;',
       'sqcap' => '&#x02293;',
       'sqcaps' => '&#x02293;&#x0FE00;',
       'sqcup' => '&#x02294;',
       'sqcups' => '&#x02294;&#x0FE00;',
       'sqsub' => '&#x0228F;',
       'sqsube' => '&#x02291;',
       'sqsubset' => '&#x0228F;',
       'sqsubseteq' => '&#x02291;',
       'sqsup' => '&#x02290;',
       'sqsupe' => '&#x02292;',
       'sqsupset' => '&#x02290;',
       'sqsupseteq' => '&#x02292;',
       'squ' => '&#x025A1;',
       'square' => '&#x025A1;',
       'squarf' => '&#x025AA;',
       'squf' => '&#x025AA;',
       'srarr' => '&#x02192;&#x0FE00;',
       'sscr' => '&#x1D4C8;',
       'ssetmn' => '&#x02216;&#x0FE00;',
       'sstarf' => '&#x022C6;',
       'star' => '&#x022C6;',
       'starf' => '&#x02605;',
       'straightepsilon' => '&#x003B5;',
       'straightphi' => '&#x003C6;',
       'sub' => '&#8834;',
       'subE' => '&#x02286;',
       'subdot' => '&#x02ABD;',
       'sube' => '&#8838;',
       'subedot' => '&#x02AC3;',
       'submult' => '&#x02AC1;',
       'subnE' => '&#x0228A;',
       'subne' => '&#x0228A;',
       'subplus' => '&#x02ABF;',
       'subrarr' => '&#x02979;',
       'subset' => '&#x02282;',
       'subseteq' => '&#x02286;',
       'subseteqq' => '&#x02286;',
       'subsetneq' => '&#x0228A;',
       'subsetneqq' => '&#x0228A;',
       'subsim' => '&#x02AC7;',
       'subsub' => '&#x02AD5;',
       'subsup' => '&#x02AD3;',
       'succ' => '&#x0227B;',
       'succapprox' => '&#x0227F;',
       'succcurlyeq' => '&#x0227D;',
       'succeq' => '&#x0227D;',
       'succnapprox' => '&#x022E9;',
       'succneqq' => '&#x02AB6;',
       'succnsim' => '&#x022E9;',
       'succsim' => '&#x0227F;',
       'sum' => '&#8721;',
       'sung' => '&#x0266A;',
       'sup' => '&#8835;',
       'sup1' => '&#185;',
       'sup2' => '&#178;',
       'sup3' => '&#179;',
       'supE' => '&#x02287;',
       'supdot' => '&#x02ABE;',
       'supdsub' => '&#x02AD8;',
       'supe' => '&#8839;',
       'supedot' => '&#x02AC4;',
       'suphsol' => '&#x02283;&#x0002F;',
       'suphsub' => '&#x02AD7;',
       'suplarr' => '&#x0297B;',
       'supmult' => '&#x02AC2;',
       'supnE' => '&#x0228B;',
       'supne' => '&#x0228B;',
       'supplus' => '&#x02AC0;',
       'supset' => '&#x02283;',
       'supseteq' => '&#x02287;',
       'supseteqq' => '&#x02287;',
       'supsetneq' => '&#x0228B;',
       'supsetneqq' => '&#x0228B;',
       'supsim' => '&#x02AC8;',
       'supsub' => '&#x02AD4;',
       'supsup' => '&#x02AD6;',
       'swArr' => '&#x021D9;',
       'swarhk' => '&#x02926;',
       'swarr' => '&#x02199;',
       'swarrow' => '&#x02199;',
       'swnwar' => '&#x0292A;',
       'szlig' => '&#223;',
       'target' => '&#x02316;',
       'tau' => '&#964;',
       'tbrk' => '&#x023B4;',
       'tcaron' => '&#x00165;',
       'tcedil' => '&#x00163;',
       'tcy' => '&#x00442;',
       'tdot' => '&#x020DB;',
       'telrec' => '&#x02315;',
       'tfr' => '&#x1D531;',
       'there4' => '&#8756;',
       'therefore' => '&#x02234;',
       'theta' => '&#952;',
       'thetasym' => '&#977;',
       'thetav' => '&#x003D1;',
       'thickapprox' => '&#x02248;&#x0FE00;',
       'thicksim' => '&#x0223C;&#x0FE00;',
       'thinsp' => '&#8201;',
       'thkap' => '&#x02248;&#x0FE00;',
       'thksim' => '&#x0223C;&#x0FE00;',
       'thorn' => '&#254;',
       'tilde' => '&#732;',
       'times' => '&#215;',
       'timesb' => '&#x022A0;',
       'timesbar' => '&#x02A31;',
       'timesd' => '&#x02A30;',
       'tint' => '&#x0222D;',
       'toea' => '&#x02928;',
       'top' => '&#x022A4;',
       'topbot' => '&#x02336;',
       'topcir' => '&#x02AF1;',
       'topf' => '&#x1D565;',
       'topfork' => '&#x02ADA;',
       'tosa' => '&#x02929;',
       'tprime' => '&#x02034;',
       'trade' => '&#8482;',
       'triangle' => '&#x025B5;',
       'triangledown' => '&#x025BF;',
       'triangleleft' => '&#x025C3;',
       'trianglelefteq' => '&#x022B4;',
       'triangleq' => '&#x0225C;',
       'triangleright' => '&#x025B9;',
       'trianglerighteq' => '&#x022B5;',
       'tridot' => '&#x025EC;',
       'trie' => '&#x0225C;',
       'triminus' => '&#x02A3A;',
       'triplus' => '&#x02A39;',
       'trisb' => '&#x029CD;',
       'tritime' => '&#x02A3B;',
       'tscr' => '&#x1D4C9;',
       'tscy' => '&#x00446;',
       'tshcy' => '&#x0045B;',
       'tstrok' => '&#x00167;',
       'twixt' => '&#x0226C;',
       'twoheadleftarrow' => '&#x0219E;',
       'twoheadrightarrow' => '&#x021A0;',
       'uArr' => '&#8657;',
       'uHar' => '&#x02963;',
       'uacute' => '&#250;',
       'uarr' => '&#8593;',
       'ubrcy' => '&#x0045E;',
       'ubreve' => '&#x0016D;',
       'ucirc' => '&#251;',
       'ucy' => '&#x00443;',
       'udarr' => '&#x021C5;',
       'udblac' => '&#x00171;',
       'udhar' => '&#x0296E;',
       'ufisht' => '&#x0297E;',
       'ufr' => '&#x1D532;',
       'ugrave' => '&#249;',
       'uharl' => '&#x021BF;',
       'uharr' => '&#x021BE;',
       'uhblk' => '&#x02580;',
       'ulcorn' => '&#x0231C;',
       'ulcorner' => '&#x0231C;',
       'ulcrop' => '&#x0230F;',
       'ultri' => '&#x025F8;',
       'umacr' => '&#x0016B;',
       'uml' => '&#168;',
       'uogon' => '&#x00173;',
       'uopf' => '&#x1D566;',
       'uparrow' => '&#x02191;',
       'updownarrow' => '&#x02195;',
       'upharpoonleft' => '&#x021BF;',
       'upharpoonright' => '&#x021BE;',
       'uplus' => '&#x0228E;',
       'upsi' => '&#x003C5;',
       'upsih' => '&#978;',
       'upsilon' => '&#965;',
       'upuparrows' => '&#x021C8;',
       'urcorn' => '&#x0231D;',
       'urcorner' => '&#x0231D;',
       'urcrop' => '&#x0230E;',
       'uring' => '&#x0016F;',
       'urtri' => '&#x025F9;',
       'uscr' => '&#x1D4CA;',
       'utdot' => '&#x022F0;',
       'utilde' => '&#x00169;',
       'utri' => '&#x025B5;',
       'utrif' => '&#x025B4;',
       'uuarr' => '&#x021C8;',
       'uuml' => '&#252;',
       'uwangle' => '&#x029A7;',
       'vArr' => '&#x021D5;',
       'vBar' => '&#x02AE8;',
       'vBarv' => '&#x02AE9;',
       'vDash' => '&#x022A8;',
       'vangrt' => '&#x022BE;',
       'varepsilon' => '&#x0025B;',
       'varkappa' => '&#x003F0;',
       'varnothing' => '&#x02205;',
       'varphi' => '&#x003D5;',
       'varpi' => '&#x003D6;',
       'varpropto' => '&#x0221D;',
       'varr' => '&#x02195;',
       'varrho' => '&#x003F1;',
       'varsigma' => '&#x003C2;',
       'varsubsetneq' => '&#x0228A;&#x0FE00;',
       'varsubsetneqq' => '&#x0228A;&#x0FE00;',
       'varsupsetneq' => '&#x0228B;&#x0FE00;',
       'varsupsetneqq' => '&#x0228B;&#x0FE00;',
       'vartheta' => '&#x003D1;',
       'vartriangleleft' => '&#x022B2;',
       'vartriangleright' => '&#x022B3;',
       'vcy' => '&#x00432;',
       'vdash' => '&#x022A2;',
       'vee' => '&#x02228;',
       'veebar' => '&#x022BB;',
       'veeeq' => '&#x0225A;',
       'vellip' => '&#x022EE;',
       'verbar' => '&#x0007C;',
       'vert' => '&#x0007C;',
       'vfr' => '&#x1D533;',
       'vltri' => '&#x022B2;',
       'vnsub' => '&#x02284;',
       'vnsup' => '&#x02285;',
       'vopf' => '&#x1D567;',
       'vprop' => '&#x0221D;',
       'vrtri' => '&#x022B3;',
       'vscr' => '&#x1D4CB;',
       'vsubnE' => '&#x0228A;&#x0FE00;',
       'vsubne' => '&#x0228A;&#x0FE00;',
       'vsupnE' => '&#x0228B;&#x0FE00;',
       'vsupne' => '&#x0228B;&#x0FE00;',
       'vzigzag' => '&#x0299A;',
       'wcirc' => '&#x00175;',
       'wedbar' => '&#x02A5F;',
       'wedge' => '&#x02227;',
       'wedgeq' => '&#x02259;',
       'weierp' => '&#8472;',
       'wfr' => '&#x1D534;',
       'wopf' => '&#x1D568;',
       'wp' => '&#x02118;',
       'wr' => '&#x02240;',
       'wreath' => '&#x02240;',
       'wscr' => '&#x1D4CC;',
       'xcap' => '&#x022C2;',
       'xcirc' => '&#x025EF;',
       'xcup' => '&#x022C3;',
       'xdtri' => '&#x025BD;',
       'xfr' => '&#x1D535;',
       'xhArr' => '&#x0F57B;',
       'xharr' => '&#x0F578;',
       'xi' => '&#958;',
       'xlArr' => '&#x0F579;',
       'xlarr' => '&#x0F576;',
       'xmap' => '&#x0F57D;',
       'xnis' => '&#x022FB;',
       'xodot' => '&#x02299;',
       'xopf' => '&#x1D569;',
       'xoplus' => '&#x02295;',
       'xotime' => '&#x02297;',
       'xrArr' => '&#x0F57A;',
       'xrarr' => '&#x0F577;',
       'xscr' => '&#x1D4CD;',
       'xsqcup' => '&#x02294;',
       'xuplus' => '&#x0228E;',
       'xutri' => '&#x025B3;',
       'xvee' => '&#x022C1;',
       'xwedge' => '&#x022C0;',
       'yacute' => '&#253;',
       'yacy' => '&#x0044F;',
       'ycirc' => '&#x00177;',
       'ycy' => '&#x0044B;',
       'yen' => '&#165;',
       'yfr' => '&#x1D536;',
       'yicy' => '&#x00457;',
       'yopf' => '&#x1D56A;',
       'yscr' => '&#x1D4CE;',
       'yucy' => '&#x0044E;',
       'yuml' => '&#255;',
       'zacute' => '&#x0017A;',
       'zcaron' => '&#x0017E;',
       'zcy' => '&#x00437;',
       'zdot' => '&#x0017C;',
       'zeetrf' => '&#x02128;',
       'zeta' => '&#950;',
       'zfr' => '&#x1D537;',
       'zhcy' => '&#x00436;',
       'zigrarr' => '&#x021DD;',
       'zopf' => '&#x1D56B;',
       'zscr' => '&#x1D4CF;',
       'zwj' => '&#8205;',
       'zwnj' => '&#8204;',
      );

    %numcodes_vs_entities = ();
    foreach my $entity (keys(%entities_vs_numcodes))
      {
	$numcodes_vs_entities{$entities_vs_numcodes{$entity}} = $entity;
      }

    %entities_vs_chars =
      (
       "amp" => "&",
       "lt" => "<",
       "gt" => ">",
       "iexcl" => "¡",
       "cent" => "¢",
       "pound" => "£",
       "curren" => "¤",
       "yen" => "¥",
       "brvbar" => "¦",
       "sect" => "§",
       "uml" => "¨",
       "copy" => "©",
       "ordf" => "ª",
       "laquo" => "«",
       "not" => "¬",
       "shy" => "­",
       "reg" => "®",
       "macr" => "¯",
       "deg" => "°",
       "plusmn" => "±",
       "sup2" => "²",
       "sup3" => "³",
       "acute" => "´",
       "micro" => "µ",
       "para" => "¶",
       "middot" => "·",
       "cedil" => "¸",
       "sup1" => "¹",
       "ordm" => "º",
       "raquo" => "»",
       "frac14" => "¼",
       "frac12" => "½",
       "frac34" => "¾",
       "iquest" => "¿",
       "Agrave" => "À",
       "Aacute" => "Á",
       "Acirc" => "Â",
       "Atilde" => "Ã",
       "Auml" => "Ä",
       "Aring" => "Å",
       "AElig" => "Æ",
       "Ccedil" => "Ç",
       "Egrave" => "È",
       "Eacute" => "É",
       "Ecirc" => "Ê",
       "Euml" => "Ë",
       "Igrave" => "Ì",
       "Iacute" => "Í",
       "Icirc" => "Î",
       "Iuml" => "Ï",
       "ETH" => "Ð",
       "Ntilde" => "Ñ",
       "Ograve" => "Ò",
       "Oacute" => "Ó",
       "Ocirc" => "Ô",
       "Otilde" => "Õ",
       "Ouml" => "Ö",
       "times" => "×",
       "Oslash" => "Ø",
       "Ugrave" => "Ù",
       "Uacute" => "Ú",
       "Ucirc" => "Û",
       "Uuml" => "Ü",
       "Yacute" => "Ý",
       "THORN" => "Þ",
       "szlig" => "ß",
       "agrave" => "à",
       "aacute" => "á",
       "acirc" => "â",
       "atilde" => "ã",
       "auml" => "ä",
       "aring" => "å",
       "aelig" => "æ",
       "ccedil" => "ç",
       "egrave" => "è",
       "eacute" => "é",
       "ecirc" => "ê",
       "euml" => "ë",
       "igrave" => "ì",
       "iacute" => "í",
       "icirc" => "î",
       "iuml" => "ï",
       "eth" => "ð",
       "ntilde" => "ñ",
       "ograve" => "ò",
       "oacute" => "ó",
       "ocirc" => "ô",
       "otilde" => "õ",
       "ouml" => "ö",
       "divide" => "÷",
       "oslash" => "ø",
       "ugrave" => "ù",
       "uacute" => "ú",
       "ucirc" => "û",
       "uuml" => "ü",
       "yacute" => "ý",
       "thorn" => "þ",
       "yuml" => "ÿ",
      );

    %chars_vs_entities = ();
    foreach my $char (keys(%entities_vs_chars))
      {
	$chars_vs_entities{$entities_vs_chars{$char}} = $char;
      }

    $_entity_name_regexp = '[a-zA-Z0-9]+';
    $_entity_regexp = '&' . $_entity_name_regexp . ';';

    $_numcode_value_regexp = '(?:x[0-9a-fA-F]+|[0-9]+)';
    $_numcode_regexp = '&#' . $_numcode_value_regexp . ';';

    $init_done = 1;
  }

sub reset_init
  {
    $init_done = 0;
  }

sub _entities_to_numcodes
  #a ($str_ref, $protected_entities)
  # Internal auxiliary function used by `entities_to_numcodes`. $str_ref is a reference to a
  # string. In this string, all known entities are replaced by numcodes "Known" means
  # contained in @entities_vs_numcodes. Unknown entities are left unchanged. Returns
  # $str_ref again. Note that the string $str_ref points to is altered by this function. By
  # $protected_entities, entities that are to be excluded from the replacement can be
  # specified. If set, $protected_entities must be a reference to a list of entity
  # names. Each entity on the list is not replaced by the respective numerical code.
  {
    my ($str_ref, $protected_entities) = @_;

    my $process_entity =
      sub
	{
	  my ($entity, $entity_name) = @_;
	  if ( ( $protected_entities ) && ( grep($entity_name eq $_, @{$protected_entities}) ) )
	    {
	      return($entity);
	    }
	  else
	    {
	      my $numcode = $entities_vs_numcodes{$entity_name};
	      return($numcode or $entity);
	    }
	};

#    ${$str_ref} =~ s/&([^#;][^;]*);/&{$process_entity}($&, $1)/eg;
    ${$str_ref} =~ s/&($_entity_name_regexp);/&{$process_entity}($&, $1)/eg;

    return($str_ref);
  }

sub entities_to_numcodes
  #a ($str_or_ref)
  # Substitutes all entities in a string by numcodes. The string is specified by
  # $str_or-ref, which may be the string itself or a reference to the string. If $str_or_ref
  # is a string, the converted string is returned and the original string is not altered. If
  # $str_ref is a reference, the original string is altered and a reference to it is
  # returned. Only known entities can be replaced. "Known" means contained in
  # @entities_vs_numcodes. Unknown entities are left unchanged.  By $protected_entities,
  # entities that are to be excluded from the replacement can be specified. If set,
  # $protected_entities must be a reference to a list of entity names. Each entity on the
  # list is not replaced by the respective numerical code.
  {
    my ($str_or_ref, $protected_entities) = @_;
    if ( ref($str_or_ref) )
      {
	return(_entities_to_numcodes($str_or_ref, $protected_entities));
      }
    else
      {
	return(${_entities_to_numcodes(\$str_or_ref, $protected_entities)});
      }
  }

sub _numcodes_to_entities
  #a ($str_ref, $protected_numcodes)
  # Internal auxiliary function used by `numcodes_to_entities`. $str_ref is a reference to a
  # string. In this string, all known numerical codes are replaced by entities. "Known"
  # means contained in @numcodes_vs_entities. Unknown numerical codes are left unchanged.
  # Returns $str_ref again. Note that the string $str_ref points to is altered by this
  # function. By $protected_numcodes, numerical codes that are to be excluded from the
  # replacement can be specified. If set, $protected_numcodes must be a reference to a list
  # of numerical codes. Each numerical code on the list is not replaced by the respective
  # entity.
  {
    my ($str_ref, $protected_numcodes) = @_;

    my $process_numcode =
      sub
	{
	  my ($numcode) = @_;
	  if ( ( $protected_numcodes ) && ( grep($numcode eq $_, @{$protected_numcodes}) ) )
	    {
	      return($numcode);
	    }
	  else
	    {
	      my $entity_name = $numcodes_vs_entities{$numcode};
	      my $entity = '&' . $entity_name . ';';
	      return($entity or $numcode);
	    }
	};

#    $ {$str_ref} =~ s/&#[^;]+;/&{$process_entity}($&)/eg;
    $ {$str_ref} =~ s/$_numcode_regexp/&{$process_entity}($&)/eg;

    return($str_ref);
  }

sub numcodes_to_entities
  #a ($str_or_ref, $protected_numcodes)
  # Substitutes all numerical codes in a string by entities. The string is specified by
  # $str_or-ref, which may be the string itself or a reference to the string. If $str_or_ref
  # is a string, the converted string is returned and the original string is not altered. If
  # $str_ref is a reference, the original string is altered and a reference to it is
  # returned.  Only known numerical codes can be replaced. "Known" means contained in
  # @numcodes_vs_entities. Unknown numerical codes are left unchanged. By
  # $protected_numcodes, numerical codes that are to be excluded from the replacement can be
  # specified. If set, $protected_numcodes must be a reference to a list of numerical
  # codes. Each numerical code on the list is not replaced by the respective entity.
  {
    my ($str_or_ref, $protected_numcodes) = @_;
    if ( ref($str_or_ref) )
      {
	return(_numcodes_to_entities($str_or_ref, $protected_numcodes));
      }
    else
      {
	return(${_numcodes_to_entities(\$str_or_ref, $protected_numcodes)});
      }
  }

sub _chars_to_numcodes
  #a ($str_ref, $protected_chars, $mode) 
  # Internal auxiliary function used by `chars_to_numcodes`. $str_ref is a reference to a
  # string. In this string, all known special characters are replaced by numerical
  # codes. "Known" means contained in @chars_vs_entities. Unknown special characters are
  # left unchanged. Returns $str_ref again. Note that the string $str_ref points to is
  # altered by this function. By $protected_chars, characters that are to be excluded from
  # the replacement can be specified. If set, $protected_chars must be a string or a
  # reference to a list of characters. Each character in the string or list is not replaced
  # by the respective numerical code. $mode controls if &'s starting entities or numerical
  # codes are preserved or not. If $mode is 'RESPECT_QUTING', they are preserved, if $mode
  # is 'NORMAL', they are relaced as well (unless "&" is in $protected_chars). Default is
  # 'NORMAL'.
  {
    my ($str_ref, $protected_chars, $mode) = @_;
    $protected_chars = join('', @{$protected_chars}) if ( ref($protected_chars) );
    $mode ||= 'NORMAL';
    my $chars = join('', keys(%chars_vs_entities));
    $chars =~ s/[$protected_chars]//g if ( $protected_chars );

    my $process_char =
      sub
	{
	  my $char = $_[0];
	  my $numcode = $entities_vs_numcodes{$chars_vs_entities{$char}};
	  return($numcode);
	};

    if ( $mode eq 'NORMAL' )
      {
	$ {$str_ref} =~ s/[$chars]/&{$process_char}($&)/eg;
      }
    elsif ( $mode eq 'RESPECT_QUOTING' )
      {
	$ {$str_ref} =~ s/($_entity_regexp)|($_numcode_regexp)|([$chars])/
	  $1 or $2 or &{$process_char}($3)/eg;
      }

    return($str_ref);
  }

sub chars_to_numcodes
  #a ($str_or_ref, $protected_chars, $mode)
  # Substitutes all known special characters in a string by numerical codes. The string is
  # specified by $str_or-ref, which may be the string itself or a reference to the
  # string. If $str_or_ref is a string, the converted string is returned and the original
  # string is not altered. If $str_ref is a reference, the original string is altered and a
  # reference to it is returned. Only known special characters can be replaced. "Known"
  # means contained in @chars_vs_entities. Unknown special characters are left unchanged. By
  # $protected_chars, characters that are to be excluded from the replacement can be
  # specified. If set, $protected_chars must be a string or a reference to a list of
  # characters. Each character in the string or list is not replaced by the respective
  # numerical code. $mode controls if &'s starting entities or numerical codes are preserved
  # or not. If $mode is 'RESPECT_QUTING', they are preserved, if $mode is 'NORMAL', they are
  # relaced as well (unless "&" is in $protected_chars). Default is 'NORMAL'.
  #
  # Examples:
  #
  #   $bar = chars_to_numcodes($foo);
  #
  # Replaces all known special characters in $foo by numerical codes, writes the result into
  # $bar, leaves $foo unchanged.
  #
  #   chars_to_numcodes(\$foo, '<>&');
  #
  # Replaces all known special characters in $foo except <, >, &. $foo is altered.
  #
  #   chars_to_numcodes(\$foo, ['<', '>', '&']);
  #
  # The same.
  {
    my ($str_or_ref, $protected_chars, $mode) = @_;
    if ( ref($str_or_ref) )
      {
	return(_chars_to_numcodes($str_or_ref, $protected_chars, $mode));
      }
    else
      {
	return(${_chars_to_numcodes(\$str_or_ref, $protected_chars, $mode)});
      }
  }

sub _numcodes_to_chars
  #a ($str_ref, $protected_numcodes))
  # Internal auxiliary function used by `numcodes_to_chars`. $str_ref is a reference to a
  # string. In this string, known numerical codes are replaced by characters. "Known" means
  # contained in @entities_vs_chars. Unknown numerical codes are left unchanged. Returns
  # $str_ref again. Note that the string $str_ref points to is altered by this function. By
  # $protected_numcodes, numerical codes that are to be excluded from the replacement can be
  # specified. If set, $protected_numcodes must be a reference to a list of numerical codes
  # Each numerical code in the list is not replaced by the respective character. This may be
  # usefull if you want to prevent the entities that quote the XML special characters (i.e.,
  # &lt;, &gt;, &amp;) from being replaced, for example.
  {
    my ($str_ref, $protected_numcodes) = @_;

    my $process_numcode =
      sub
	{
	  my ($numcode) = @_;
	  if ( ( $protected_numcodes ) && ( grep($numcode eq $_, @{$protected_numcodes}) ) )
	    {
	      return($numcode);
	    }
	  else
	    {
	      my $char = $entities_vs_chars{$numcodes_vs_entities{$numcode}};
	      return($char or $numcode);
	    }
	};

    ${$str_ref} =~ s/$_numcode_regexp/&{$process_numcode}($&)/eg;

    return($str_ref);
  }

sub numcodes_to_chars
  #a ($str_or_ref, $protected_numcodes)

  # Substitutes numerical codes in a string by characters. The string is specified by
  # $str_or_ref, which may be the string itself or a reference to the string. If $str_or_ref
  # is a string, the converted string is returned and the original string is not altered. If
  # $str_ref is a reference, the original string is altered and a reference to it is
  # returned.  Only known numerical codes can be replaced. "Known" means contained in
  # @numcodes_vs_chars. Unknown numerical codes are left unchanged. By $protected_numcodes,
  # numerical codes that are to be excluded from the replacement can be specified. If set,
  # $protected_numcodes must be a reference to a list of numerical codes. Each numerical
  # code on the list is not replaced by the respective character.
  #
  # Examples:
  #c
  #   $bar = numcodes_to_chars($foo);
  #/c
  # Replaces all known numerical codes in $foo by characters, writes the result into $bar,
  # leaves $foo unchanged.
  #c
  #   numcodes_to_chars(\$foo, ['lt', 'gt', 'amp']);
  #/c
  # Replaces all known numerical codes in $foo except &lt;, &gt;, &amp; (may be usefull if
  # you want to prevent the XML special characters, i.e., <, >, &, from occurring in the
  # result). $foo is alterd.
  {
    my ($str_or_ref, $protected_numcodes) = @_;
    if ( ref($str_or_ref) )
      {
	return(_numcodes_to_chars($str_or_ref, $protected_numcodes));
      }
    else
      {
	return(${_numcodes_to_chars(\$str_or_ref, $protected_numcodes)});
      }
  }

sub _entities_to_chars
  #a ($str_ref, $protected_entities))

  # Internal auxiliary function used by `entities_to_chars`. $str_ref is a reference to a
  # string. In this string, known entities are replaced by characters. "Known" means
  # contained in @entities_vs_chars. Unknown entities are left unchanged. Returns $str_ref
  # again. Note that the string $str_ref points to is altered by this function. By
  # $protected_entities, entities that are to be excluded from the replacement can be
  # specified. If set, $protected_entities must be a reference to a list of entity
  # names. Each entity on the list is not replaced by the respective character. This may be
  # usefull if you want to prevent the entities that quote the XML special characters (i.e.,
  # &lt;, &gt;, &amp;) from being replaced, for example.
  {
    my ($str_ref, $protected_entities) = @_;

    my $process_entity =
      sub
	{
	  my ($entity, $entity_name) = @_;
	  if ( ( $protected_entities ) && ( grep($entity_name eq $_, @{$protected_entities}) ) )
	    {
	      return($entity);
	    }
	  else
	    {
	      my $char = $entities_vs_chars{$entity_name};
	      return($char or $entity);
	    }
	};

#    ${$str_ref} =~ s/&([^#;][^;]*);/&{$process_entity}($&, $1)/eg;
    ${$str_ref} =~ s/&($_entity_name_regexp);/&{$process_entity}($&, $1)/eg;

    return($str_ref);
  }

sub entities_to_chars
  #a ($str_or_ref, $protected_entities)
  # Substitutes entities in a string by characters. The string is specified by $str_or_ref,
  # which may be the string itself or a reference to the string. If $str_or_ref is a string,
  # the converted string is returned and the original string is not altered. If $str_ref is
  # a reference, the original string is altered and a reference to it is returned.  Only
  # known entities can be replaced. "Known" means contained in @entities_vs_chars. Unknown
  # entities are left unchanged. By $protected_entities, entities that are to be excluded
  # from the replacement can be specified. If set, $protected_entities must be a reference
  # to a list of entity names. Each entity on the list is not replaced by the respective
  # character.
  #
  # Examples:
  #c
  #   $bar = entities_to_chars($foo);
  #/c
  # Replaces all known entities in $foo by characters, writes the result into $bar, leaves
  # $foo unchanged.
  #c
  #   entities_to_chars(\$foo, ['lt', 'gt', 'amp']);
  #/c
  # Replaces all known entities in $foo except &lt;, &gt;, &amp; (may be usefull if you want
  # to prevent the XML special characters, i.e., <, >, &, from occurring in the
  # result). $foo is alterd.
  {
    my ($str_or_ref, $protected_entities) = @_;
    if ( ref($str_or_ref) )
      {
	return(_entities_to_chars($str_or_ref, $protected_entities));
      }
    else
      {
	return(${_entities_to_chars(\$str_or_ref, $protected_entities)});
      }
  }

sub _chars_to_entities
  #a ($str_ref, $protected_chars, $mode)
  # Internal auxiliary function used by `chars_to_entities`. $str_ref is a reference to a
  # string. In this string, all known special characters are replaced by entities. "Known"
  # means contained in @chars_vs_entities. Unknown special characters are left unchanged.
  # Returns $str_ref again. Note that the string $str_ref points to is altered by this
  # function. By $protected_chars, characters that are to be excluded from the replacement
  # can be specified. If set, $protected_chars must be a string or a reference to a list of
  # characters. Each character in the string or list is not replaced by the respective
  # entity. $mode conroles how to deal with special characters that are part of entity or
  # numerical code references, i.e., &name; or &#number;. If $mode is "NORMAL" (the
  # default), they are replaced as well, if $mode is "RESPECT_QUOTING", they are left
  # unchanged.
  {
    my ($str_ref, $protected_chars, $mode) = @_;
    $protected_chars = join('', @{$protected_chars}) if ( ref($protected_chars) );
    $mode ||= 'NORMAL';
    my $chars = join('', keys(%chars_vs_entities));
    $chars =~ s/[$protected_chars]//g if ( $protected_chars );
    my $regexp = "[$chars]";

    my $process_char =
      sub
	{
	  my $char = $_[0];
	  my $entity = '&' . $chars_vs_entities{$char} . ';';
	  return($entity);
	};

    if ( $mode eq 'NORMAL' )
      {
	$ {$str_ref} =~ s/[$chars]/&{$process_char}($&)/eg;
      }
    elsif ( $mode eq 'RESPECT_QUOTING' )
      {
	$ {$str_ref} =~ s/($_entity_regexp)|($_numcode_regexp)|([$chars])/
	  $1 or $2 or &{$process_char}($3)/eg;
      }

    return($str_ref);
  }

sub chars_to_entities
  #a ($str_or_ref, $protected_chars, $mode)
  # Substitutes all known special characters in a string by entities. The string is
  # specified by $str_or-ref, which may be the string itself or a reference to the
  # string. If $str_or_ref is a string, the converted string is returned and the original
  # string is not altered. If $str_ref is a reference, the original string is altered and a
  # reference to it is returned. Only known special characters can be replaced. "Known"
  # means contained in @chars_vs_entities. Unknown special characters are left unchanged.By
  # $protected_chars, characters that are to be excluded from the replacement can be
  # specified. If set, $protected_chars must be a string or a reference to a list of
  # characters. Each character in the string or list is not replaced by the respective
  # entity.  $mode conroles how to deal with special characters that are part of entity or
  # numerical code references, i.e., &name; or &#number;. If $mode is "NORMAL" (the
  # default), they are replaced as well, if $mode is "RESPECT_QUOTING", they are left
  # unchanged.
  {
    my ($str_or_ref, $protected_chars, $mode) = @_;
    if ( ref($str_or_ref) )
      {
	return(_chars_to_entities($str_or_ref, $protected_chars, $mode));
      }
    else
      {
	return(${_chars_to_entities(\$str_or_ref, $protected_chars, $mode)});
      }
  }

sub _quote_xml
  #a ($str_ref, $how)
  # Internal auxiliary function used by `quote_xml`. $str_ref is a reference to a string. In
  # this string, all XML special characters, i.e., <, >, &, are quoted by replacing them by
  # the respective entities or numerical codes. Whether entities or numerical codes are
  # used, is controled by $how, which may be "BY_NUMCODES" or "BY_ENTITIES" (meaning is
  # self-explanatory).
  {
    my ($str_ref, $how) = @_;
    $how ||= 'BY_NUMCODES';
    if ( $how eq 'BY_NUMCODES' )
      {
	$ {$str_ref} =~ s/[<>&]/$entities_vs_numcodes{$chars_vs_entities{$&}}/eg;
      }
    elsif ( $how eq 'BY_ENTITIES' )
      {
	$ {$str_ref} =~ s/[<>&]/'&'.$chars_vs_entities{$&}.';'/eg;
      }
    return($str_ref);
  }

sub quote_xml
  #a ($str_or_ref, $how)
  # Quotes all XML special characters, i.e., <, >, &, in a string. Quoting means replacing
  # them by the respective numerical codes or entities. Whether numerical codes or entities
  # are used, is controled by $how, which may be "BY_NUMCODES" or "BY_ENTITIES" (meaning is
  # self-explanatory). The string is specified by $str_or_ref, which may be the string
  # itself or a reference to the string. If $str_or_ref is a string, the converted string is
  # returned and the original string is not altered. If $str_ref is a reference, the
  # original string is altered and a reference to it is returned.
  {
    my $str_or_ref = $_[0];
    if ( ref($str_or_ref) )
      {
	return(_quote_xml($str_or_ref));
      }
    else
      {
	return(${_quote_xml(\$str_or_ref)});
      }
  }

init();
return(1);
