# -*- shell-script -*-

# Author: Tilman Rassy <rassy@math.tu-berlin.de>
# $Id: mmcdk.init.tpl,v 1.34 2009/05/15 23:15:12 rassy Exp $

# Mmcdk init file
#
# This is a Bash code file
#
# Loads the mmcdk commands, sets configuration parameters as Java system
# properties, loads the site-local init file if existing, loads the
# user-specific init file if existing.
#
# It is recommended that you do not edit this file directly. Your changes will
# be lost in the next update. Instead, put your changes in a separate file
# local_mmcdk.init and place it in the same directory at this file. If existing,
# local_mmcdk.init is sourced by this file.
#
# This file is sourced by the mmjvmd init file, <prefix>/etc/mmjvmd/mmjvmd.init,
# where <prefix> stands for the common install prefix of all Mumie packages.

# Auxiliary variables:
checkin_root=${MM_CHECKIN_ROOT:-@checkin-root@}
xsl_lib_dir=$prefix/lib/mmcdk/xsl
master_to_tmp=file://$xsl_lib_dir/master2tmp.xsl
xsl_tmp_to_preview=file://$xsl_lib_dir/rootxsl_mmcdk.xsl
pge_tmp_to_preview=file://$checkin_root/system/misc/xsl_page.preview.xsl
css_tmp_to_preview=file://$checkin_root/system/misc/xsl_css.preview.xsl
elm_tmp_to_preview=file://$checkin_root/system/element/xsl_element.preview.xsl
prb_tmp_to_preview=file://$checkin_root/system/problem/xsl_problem.preview.xsl
crs_tmp_to_preview=file://$checkin_root/system/course/xsl_course_nav.preview.xsl
sum_tmp_to_preview=file://$checkin_root/system/course/xsl_summary.preview.xsl
js_lib_tmp_to_preview=file://$checkin_root/system/misc/xsl_text.preview.xsl

# Load commands:
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmprev
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmckrefs
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmjava
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmalias
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmsrv
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmckin
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmroot
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmjmtag
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmlsrefs
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmgendoc
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmr2gdoc
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmlsprev
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmgdimc
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmdatasheet
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmencrypt
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmsec
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmimg
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmstorepass
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmclearpass
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmckgdim
mmjvmc loadcmd net.mumie.cdk.cmdlib.Mmcksecmaster

# Checkin root:
mmjvmc setprop net.mumie.cdk.checkinRoot=$checkin_root

# Install prefix:
mmjvmc setprop net.mumie.cdk.installPrefix=$prefix

# Stylesheet for transforming master plus content to temporary XML:
mmjvmc setprop net.mumie.cdk.masterToTmpURI=$master_to_tmp

# Stylesheets for transforming temporary XML to preview:
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.xsl_stylesheet=$xsl_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.page=$pge_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.css_stylesheet=$css_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.element=$elm_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.subelement=$elm_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.problem=$prb_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.course=$crs_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.course_section=$crs_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.worksheet=$crs_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.summary=$sum_tmp_to_preview
mmjvmc setprop net.mumie.cdk.tmpToPreviewURI.js_lib=$js_lib_tmp_to_preview

# Suffixes for content files:
mmjvmc setprop net.mumie.cdk.contentTypeSuffix.applet=jar
mmjvmc setprop net.mumie.cdk.contentTypeSuffix.java_class=class

# Suffixes for preview files:
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.xsl_stylesheet=xsl
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.page=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.css_stylesheet=css
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.element=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.subelement=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.problem=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.course=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.course_section=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.worksheet=xhtml
mmjvmc setprop net.mumie.cdk.previewTypeSuffix.js_lib=js

# Suffixes of source files:
mmjvmc setprop net.mumie.cdk.sourceTypeSuffix.element=tex
mmjvmc setprop net.mumie.cdk.sourceTypeSuffix.subelement=tex
mmjvmc setprop net.mumie.cdk.sourceTypeSuffix.applet=java
mmjvmc setprop net.mumie.cdk.sourceTypeSuffix.java_class=java

# Set jarsigner alias and keystore password:
mmjvmc setprop net.mumie.cdk.jarsignKeystorePassword=@signjar-storepass@
mmjvmc setprop net.mumie.cdk.jarsignKeyAlias=@signjar-alias@

# Set language codes (needed only to strip language codes from filenames):
mmjvmc setprop net.mumie.cdk.langCodes=@lang-codes@

# Set the default language if necessary:
[ "$MM_LANG" ] && mmjvmc setprop net.mumie.cdk.langCode=$MM_LANG

# Source site-local init file if existing:
local_mmcdk_init_file=$prefix/etc/mmcdk/local_mmcdk.init
[ -e $local_mmcdk_init_file ] && source $local_mmcdk_init_file

# Source user-specific init file if existing:
mmcdk_user_init_file=$mmcdk_dir/mmcdk.init # (mmcdk_dir is defined in mmcdk.conf)
[ -e $mmcdk_user_init_file ] && source $mmcdk_user_init_file
