#!/usr/bin/perl -w

#           Christian Ruppert<ruppert@math.tu-berlin.de>

# $Id: clear_log,v 1.1 2003/09/16 20:39:47 ruppert Exp $

# The MIT License (MIT)
# 
# Copyright (c) 2010 Technische Universitaet Berlin
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# ------------------
# Description
# ------------------
# Just a short workaround, may be called before a cvs update to prevent all this
# annoying ?tree_items001.js  messages (because the data files are not in the CVS)
# The index should not point to empty files, so we clear it too..


use Env qw(HOME PATH MMTEX_HOME);


# Variable defintion
#----------------------------------------------#
$folder      = "$MMTEX_HOME/utils/vardump/tigra_tree";  # relative or absolute folder to the js_files
$nav_dual    = "$folder/navigation_dualview.html";      # dualview index file
$nav_single  = "$folder/navigation_single.html";       # single view index file


for($index = 0; $index < 1000; $index++)
  {

    my $filename = "$folder/tree_items" . sprintf("%03d",$index) .".js";
    system("rm $filename") if -w $filename;

  }

# Removes all index entries from the html files..

    foreach ('SINGLE', 'DUAL')
      {
	(open(FH, "+< $nav_dual")   || die("Can't open $nav_dual"))   if $_ eq 'DUAL';
	(open(FH, "+< $nav_single") || die("Can't open $nav_single")) if $_ eq 'SINGLE';

	my $content = join("",<FH>);
	$content =~ s!<ul>([\w\W]*?)</ul>!<ul></ul>!;
	seek(FH,0,0);
	print FH $content;
	truncate(FH, tell(FH));
	close FH;
      }

