<?xml version="1.0" encoding="ASCII"?>


<!--
  The MIT License (MIT)
  
  Copyright (c) 2010 Technische Universitaet Berlin
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
-->

<!--
  @Template@
  $Id: components.xml.tpl,v 1.4 2007/07/25 11:34:00 rassy Exp $
  
  Please do not edit this file. Your changes would be overwritten in the next build.
  Instaed, create a file "components.local.xml" and define your components there.
-->

<!DOCTYPE components
   SYSTEM "file://@basedir@/etc/components.dtd">

<components xmlns="http://www.mumie.net/xml-namespace/log-analyser-components">
  <parser name="default" class="net.mumie.japs.log.analyse.parse.DefaultLogOutputParser"/>
  <filter name="field" class="net.mumie.japs.log.analyse.filter.FieldLogOutputFilter"/>
  <filter name="time" class="net.mumie.japs.log.analyse.filter.TimeLogOutputFilter"/>
  <filter name="regex" class="net.mumie.japs.log.analyse.filter.RegexLogOutputFilter"/>
  <filter name="uri" class="net.mumie.japs.log.analyse.filter.UriLogOutputFilter"/>
  <filter name="thread" class="net.mumie.japs.log.analyse.filter.ThreadLogOutputFilter"/>
  <filter name="class-name" class="net.mumie.japs.log.analyse.filter.ClassNameLogOutputFilter"/>
  <filter name="sort" class="net.mumie.japs.log.analyse.filter.SortLogOutputFilter"/>
  <serializer name="text" class="net.mumie.japs.log.analyse.serialize.TextLogOutputSerializer"/>
  <serializer name="html" class="net.mumie.japs.log.analyse.serialize.HtmlLogOutputSerializer"/>
  <serializer name="time-investigation" class="net.mumie.japs.log.analyse.investigate.TimeInvestigator"/>
</components>